function [time_vec, ...
static_pressure_vec,dynamic_pressure_vec, ...
temperature_vec, ...
force_vec, ...
acceleration_vec,velocity_vec,displacement_vec, ...
volume_vec, ...
gas_internal_energy_vec,shell_kinetic_energy_vec] = ...
gun_calc_SC_ideal(shell_mass,shell_diameter, ...
initial_vol,initial_temp,initial_nitro_mass, ...
initial_velocity,initial_displacement, ...
max_num_timesteps,max_time, ...
plot_static_pressure,plot_dynamic_pressure,plot_dynamic_over_static_pressure, ...
plot_temperature, ...
plot_force, ...
plot_acceleration,plot_velocity,plot_displacement, ...
plot_gas_internal_energy,plot_shell_kinetic_energy)
%
% Consider the case of a gun, which fires a shell from a cylindrical
% bore. Given the mass and base-plate area of the shell, along with the
% initial properties of the propellant gas generated by the powder
% charge, how does the shell move during subsequent points in time?
%
% This routine is meant to answer the preceding question, given the
% following assumptions:
%
% 0) This routine will only run within a range that is above the critical
% pressure of the explosive decomposition gas mixture (hence, the "SC" in
% the routine's name, for SuperCritical).
%
% 1) The behavior of the gas behind the shell may be described by the
% ideal gas law equations, PV = nRT and U = (3/2)nRT.
%
% 2) The pressure exerted by the propellant gas on the base of the
% projectile IS weighted by Maxwell-Boltzmann considerations, i.e.
% by what fraction of gas molecules in the propellant gas are moving with
% speeds greater than or equal to that of the projectile.
%
% 3) Joule-Thomson isenthalpic effects ARE NOT fully accounted for
% during the expansion of the propellant gas. More specifically, the
% routine is set up to terminate when the critical pressure is reached.
%
% 4) The projectile starts out motionless, with zero displacement, at
% t = 0.
%
% 5) The explosive decomposition products of the propellant used for the
% shell are stoichiometrically equivalent to those of nitroglycerin.
% This assumption imposes a stoichiometry of
% 4 C_3 H_5 N_3 O_9 --> 6 N_2 + 10 H_2 O + 12 C O_2 + 1 O_2
%
%
% Input terms:
%
% shell_mass = ; shell_diameter = ;
% initial_vol = ; initial_temp = ; initial_nitro_mass = ;
% max_num_timesteps = ; max_time = ;
% plot_static_pressure = ; plot_dynamic_pressure = ; plot_dynamic_over_static_pressure = ;
% plot_temperature = ;
% plot_force = ;
% plot_acceleration = ; plot_velocity = ; plot_displacement = ;
% plot_gas_internal_energy = ; plot_shell_kinetic_energy = ;
%
%
% Usage:
%
% [time_vec,...
% static_pressure_vec,dynamic_pressure_vec,...
% temperature_vec,...
% force_vec,...
% acceleration_vec,velocity_vec,displacement_vec,...
% volume_vec,...
% gas_internal_energy_vec,shell_kinetic_energy_vec] = ...
% gun_calc_SC_ideal(shell_mass,shell_diameter,...
% initial_vol,initial_temp,initial_nitro_mass,...
% initial_velocity,initial_displacement,...
% max_num_timesteps,max_time,...
% plot_static_pressure,plot_dynamic_pressure,plot_dynamic_over_static_pressure,...
% plot_temperature,...
% plot_force,...
% plot_acceleration,plot_velocity,plot_displacement,...
% plot_gas_internal_energy,plot_shell_kinetic_energy) ;

% PROGRAMMING NOTES
%
% This code explicitly incorporates user inputs for the initial
% displacement and velocity of the shell.
%
% Note that this function has REFPROP dependencies.
%
% Assign your REFPROP directory at line 226.
%

% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
%
% Validate and Initialize
%
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

% Validate the input.

if shell_mass<=0
error( 'The shell mass must be a positive, nonzero number.' )
else
end



if shell_diameter<=0
error( 'The shell diameter must be a positive, nonzero number.' )
else
end



if initial_vol<=0
error( 'The initial volume must be a positive, nonzero number.' )
else
end



if initial_temp<=0
error( 'The initial temperature must be a positive, nonzero number.' )
else
end

if initial_nitro_mass<=0
error( 'The initial mass of nitroglycerin must be a positive, nonzero number.' )
else
end

if max_num_timesteps<=0
error( 'The number of timesteps must be a positive, nonzero number.' )
else
end

if max_time<=0
error( 'The maximum elapsed time must be a positive, nonzero number.' )
else
end

% Use the stoichiometry of nitroglycerin's explosive decomposition to find
% the inital moles of propellant gas. In the balanced equation, 29 mol of
% gas go out for every 4 mol of nitroglycerin that go in.

mol_nitro = initial_nitro_mass * (1000/1) * (1/288.088) ;

% Detremine the moles and average molar mass of the decomposition products
% of nitroglycerin.

number_of_moles_of_gas = mol_nitro * (29/4) ;

avg_NG_prod_molar_mass_kg_per_mol = (1/29)*(1/1000)*((6*28.014)+(10*18.0153)+(12*44.009)+31. 9988) ;

% Use the shell's diameter to find the shell's base plate area.

shell_area = pi * ((shell_diameter/2)^2) ;

% Initialize the vectors.

prelim_time_vec = 0: max_time / (max_num_timesteps-1): max_time ;

static_pressure_vec = nan(1,max_num_timesteps) ;

dynamic_pressure_vec = nan(1,max_num_timesteps) ;

temperature_vec = nan(1,max_num_timesteps) ;

force_vec = nan(1,max_num_timesteps) ;

acceleration_vec = nan(1,max_num_timesteps) ;

velocity_vec = nan(1,max_num_timesteps) ;

velocity_vec(1,1) = initial_velocity ;

displacement_vec = nan(1,max_num_timesteps) ;

displacement_vec(1,1) = initial_displacement ;

volume_vec = nan(1,max_num_timesteps) ;

% Set the first values of the volume and temperature vectors.

volume_vec(1,1) = initial_vol ;

temperature_vec(1,1) = initial_temp ;

% Set the gas constant.

gas_constant = 8.31447 ; % m^3 Pa mol^-1 K^-1

% Determine the starting internal energy of the gas.

gas_internal_energy_vec = nan(1,max_num_timesteps) ;

gas_internal_energy_vec(1,1) = (3/2)*number_of_moles_of_gas*gas_constant*initial_temp ;

% Initialize the kinetic energy of the shell.

shell_kinetic_energy_vec = nan(1,max_num_timesteps) ;

shell_kinetic_energy_vec(1,1) = 0 ;

% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
%
% Iterate Through Firing Process
%
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

% Make a note of the current directory, then move to the REFPROP directory
% for the following calculations.

WD = pwd ;

%%%% User, use your REFPROP directory here!!!!!!
cd('C:\Program Files (x86)\REFPROP' ) ;

P_critical = refpropm( 'P','C',0,' ',0,'nitrogen' ,'water','co2','oxygen', [0.185043,0.198330,0.58140,0.0352270]) ;
% Critical pressure

keep_iterating = 1 ;

% For each point in time:

time_itr = 0 ;

time_vec = [] ;

while keep_iterating == 1
%for time_itr = 1:1: max(size(time_vec))-1

time_itr = time_itr + 1

time_vec = horzcat(time_vec,prelim_time_vec(1,time_itr))

% Calculate the pressure of gas in the bore.

static_pressure_vec(1,time_itr) = number_of_moles_of_gas * gas_constant * temperature_vec(1,time_itr) ./ volume_vec(1,time_itr) ;

static_pressure_vec_at_time_itr = static_pressure_vec(1,time_itr)

% Calculate the pressure on the base plate of the projectile.

dynamic_pressure_vec(1,time_itr) = static_pressure_vec(1,time_itr) ...
* integral(@(vx_vec)Maxwell_Boltzmann_1D_corr(avg_NG_prod_molar_mass_kg_per_mol, temperature_vec(1,time_itr),vx_vec), velocity_vec(1,time_itr),1e6) ;

% Calculate the force acting on the projectile.

force_vec(1,time_itr) = dynamic_pressure_vec(1,time_itr) * shell_area ;

% Calculate the acceleration of the projectile.

acceleration_vec(1,time_itr) = force_vec(1,time_itr) / shell_mass ;

% Calculate the new velocity of the projectile.

velocity_vec(1,time_itr+1) = velocity_vec(1,time_itr) + ( acceleration_vec(1,time_itr) * (prelim_time_vec(1,time_itr+1)-prelim_time_vec(time_itr)) ) ;

% Calculate the new kinetic energy of the projectile.

shell_kinetic_energy_vec(1,time_itr+1) = 0.5 * shell_mass * ( (velocity_vec(1, time_itr+1)) ^ 2 ) ;

delta_E = shell_kinetic_energy_vec(1,time_itr+1) - shell_kinetic_energy_vec(1,time_itr) ;

% Calculate the new internal energy and temperature of the propellant
% gas.

gas_internal_energy_vec(1,time_itr+1) = gas_internal_energy_vec(1,time_itr) - delta_E ;

temperature_vec(1,time_itr+1) = gas_internal_energy_vec(1,time_itr+1) / ((3/2) *number_of_moles_of_gas*gas_constant) ;

% Further update the temperature if Joule-Thomson effects are
% determined to be important. This will be done on the basis of the
% pressure, via a call to REFPROP.

static_pressure_vec_at_time_itr = static_pressure_vec(1,time_itr)

if static_pressure_vec(1,time_itr) >= P_critical*1e3
if time_itr == max_num_timesteps
keep_iterating = 0 ;
else
end
else
disp( ' ')
disp( 'Pressure has fallen below critical level.' )
disp( 'Halting execution....' )
disp( ' ')
keep_iterating = 0 ;
end

% Calculate the new displacement of the projectile.

displacement_vec(1,time_itr+1) = displacement_vec(1,time_itr) + ( velocity_vec(1, time_itr) * (prelim_time_vec(1,time_itr+1)-prelim_time_vec(time_itr)) ) ;

% Calculate the new volume of gas behind the projectile.

volume_vec(1,time_itr+1) = initial_vol + ( shell_area.*displacement_vec(1,time_itr+1) ) ;

end

time_vec = horzcat(time_vec,prelim_time_vec(1,time_itr+1)) ;

shell_kinetic_energy_vec = rmmissing(shell_kinetic_energy_vec) ;

gas_internal_energy_vec = rmmissing(gas_internal_energy_vec) ;

temperature_vec = rmmissing(temperature_vec) ;

displacement_vec = rmmissing(displacement_vec) ;

volume_vec = rmmissing(volume_vec) ;

% Calculate the final pressure on the base plate of the projectile.

size_temperature_vec = size(temperature_vec)

size_volume_vec = size(volume_vec)

static_pressure_vec(1,time_itr+1) = number_of_moles_of_gas * gas_constant * temperature_vec (1,time_itr) ./ volume_vec(1,time_itr) ;

static_pressure_vec = rmmissing(static_pressure_vec) ;

dynamic_pressure_vec(1,time_itr+1) = static_pressure_vec(1,time_itr) ...
*integral(@(vx_vec)Maxwell_Boltzmann_1D(avg_NG_prod_molar_mass_kg_per_mol,temperat ure_vec (1,time_itr+1),vx_vec),velocity_vec(1,time_itr+1),1e6) ;

dynamic_pressure_vec = rmmissing(dynamic_pressure_vec) ;

% Calculate the final force acting on the projectile.

force_vec(1,time_itr+1) = dynamic_pressure_vec(1,time_itr) * shell_area ;

force_vec = rmmissing(force_vec) ;

% Calculate the final acceleration of the projectile.

acceleration_vec(1,time_itr+1) = force_vec(1,time_itr) / shell_mass ;

acceleration_vec = rmmissing(acceleration_vec) ;

% Calculate the ratio of the dynamic pressure over the static pressure.

dynamic_over_static_pressure_vec = dynamic_pressure_vec ./ static_pressure_vec ;

dynamic_over_static_pressure_vec = rmmissing(dynamic_over_static_pressure_vec) ;

velocity_vec = rmmissing(velocity_vec) ;

displacement_vec = rmmissing(displacement_vec) ;

% Return to the original working directory.

cd(WD) ;

% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
%
% Plot Results If Requested
%
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

% The following if-then-else statements will plot results for specific
% property-as-function-of-time relationships that are requested by the
% user.

if plot_static_pressure == 1
figure

size_time_vec = size(time_vec)

size_static_pressure_vec = size(static_pressure_vec)

plot(time_vec,static_pressure_vec, 'm')
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Static Pressure in Bore as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Pressure (Pa)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if plot_dynamic_pressure == 1
figure
plot(time_vec,dynamic_pressure_vec, 'Color',[75/255,150/255,1])
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Dynamic Pressure on Shell Base-Plate as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Pressure (Pa)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if or(plot_static_pressure == 1,plot_dynamic_pressure == 1)

figure

plot(time_vec,static_pressure_vec, 'm')
hold on
grid

plot(time_vec,dynamic_pressure_vec, 'Color',[75/255,150/255,1])

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Static and Dynamic Pressure as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Pressure (Pa)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

label1 = 'Static (bore) pressure' ;
label2 = 'Dynamic (baseplate) pressure'

legend(label1,label2, 'Location' ,'northeast' ,'FontSize' ,18,'FontWeight' ,'bold')
else
end

if plot_dynamic_over_static_pressure == 1
figure
plot(time_vec,dynamic_over_static_pressure_vec, 'Color',[200/255,55/255,170/255])
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = '( Dynamic / Static ) Pressure Ratio as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Dynamic / Static Pressure (no units)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if plot_temperature == 1
figure
plot(time_vec,temperature_vec, 'r')
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Temperature of Nitroglycerin Decomposition Gases as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Temperature (K)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if plot_force == 1
figure
plot(time_vec,force_vec, 'Color',[150/255,75/255,0])
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Force on Shell Base-Plate as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Force (N)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if plot_acceleration == 1
figure
plot(time_vec,acceleration_vec, 'g')
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Shell Acceleration as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Acceleration (m/s^2)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if plot_velocity == 1
figure
plot(time_vec,velocity_vec, 'b')
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Shell Velocity as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Velocity (m/s)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if plot_displacement == 1
figure
plot(time_vec,displacement_vec, 'k')
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Shell Displacement as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Displacement (m)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if plot_shell_kinetic_energy == 1
figure
plot(time_vec,shell_kinetic_energy_vec, 'Color',[150/255,0,75/255])
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.FontWeight = 'bold' ;

ax.Title.String = 'Shell Kinetic Energy as Function of Time' ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Kinetic Energy (J)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

if plot_gas_internal_energy == 1
figure
plot(time_vec,gas_internal_energy_vec, 'Color',[0,150/255,75/255])
hold on
grid

ax = gca ;

ax.FontSize = 16 ;
ax.Title.FontSize = 32 ;
ax.Title.FontWeight = 'bold';


ax.Title.String = 'Gas Internal Energy as Function of Time' ;
ax.Title.FontWeight = 'bold';

ax.XLabel.String = 'Time (s)' ;
ax.XLabel.FontSize = 20 ;
ax.XLabel.FontWeight = 'bold';

ax.YLabel.String = 'Internal Energy (J)' ;
ax.YLabel.FontSize = 20 ;
ax.YLabel.FontWeight = 'bold';

else
end

end
