function [aug_Sobol_mat]= ...
aug_sobol_select_8(rows_surf_1_x_mat_num,cols_surf_1_x_mat_num, ...
rows_surf_2_x_mat_num,cols_surf_2_x_mat_num, ...
num_points)
%
% The purpose of this function is to generate a series of quasi-randomly
% selected vectors of adjacent points on a surface, using a Sobol-set-based
% routine to choose these points.
%
% Input terms:
%
% surf_1_x_mat = ; surf_1_y_mat = ; surf_1_z_mat = ;
%
% surf_2_x_mat = ; surf_2_y_mat = ; surf_2_z_mat = ;
%
% num_points = ;
%
% where
%
% surf_1_x_mat = the meshgrid of x-coordinates of points on
% surface 1 that are being investigated;
%
% surf_1_y_mat = the meshgrid of y-coordinates of points on
% surface 1 that are being investigated;
%
% surf_1_z_mat = the meshgrid of z-coordinates of points on
% surface 1 that are being investigated;
%
%
% surf_2_x_mat = the meshgrid of x-coordinates of points on
% surface 2 that are being investigated;
%
% surf_2_y_mat = the meshgrid of y-coordinates of points on
% surface 2 that are being investigated;
%
% surf_2_z_mat = the meshgrid of z-coordinates of points on
% surface 2 that are being investigated;
%
% and
%
% num_points = the number of points that are to be
% selected on each surface.
%
%
% Output terms:
%
% aug_Sobol_mat = a matrix, where each row is structured as follows:
%
% [index_num,s1(index_num),s2(index_num),s3(index_num),s4(index_num), probability_ranking]
%
% where
%
% index_num = an integer number representing the position of the
% row within the matrix;
%
% s1(index_number) et al.
% = numbers, in the (0,1) domain, from the 4-
% dimensional Sobol set being used to select
% coordinates within a view factor problem;
%
% and
%
% probability_ranking
% = a number, in the (0,1) domain, expressing the
% probability that a given row will be accepted for
% a Monte Carlo step in a view factor calculation.
%
%
% Usage:
%
% [aug_Sobol_mat]=...
% aug_sobol_select_8(rows_surf_1_x_mat_num,cols_surf_1_x_mat_num,...
% rows_surf_2_x_mat_num,cols_surf_2_x_mat_num,...
% num_points)

% PROGRAMMING NOTES
%
% This routine contains code for handling the
% preliminary Sobol matrix with
% more-efficient use of memory.

% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
%
% Validation
%
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV

if num_points < 1
error( 'The number of points must be greater than or equal to 1.' )
else
if mod(num_points,1) > 0
error( 'The number of points must be an integer number.' )
else
end
end

num_points = int32(num_points) ;

% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
%
% Sobol Set Selection System
%
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

% Consider the following concepts:
%
% 1) A Sobol set with four dimensions, and 1000 times the
% number of rows requested, is supposed to exist.
%
% 2) Furthermore, the actual beginning of the Sobol matrix being
% generated by this routine happens somewhere within the first
% 998*(number of rows) rows of this hypothetical, ginormous Sobol set.
%
% 3) Additionally, the first 53 rows of any Sobol matrix generated by
% sobolset must be skipped, as these represent the initialization length
% of the matrix, a region in which the true quasi-random behavior of the
% Sobol set does not occur.
%

% Randomly select one run of rows within the output of Sobol set numbers.

Sobol_row_start_num = ceil( rand() * (num_points*998) ) ;

% Generate a Sobol set with 4 dimensions, i.e. the number of dimensions in
% a view factor calculation. Skip the first 53 rows worth of points, since
% these correspond to the "initialization length" of the Sobol set.

p = sobolset(4, 'skip',((4*53)+(4*Sobol_row_start_num))) ;

% Using that Sobol set, create a matrix with 4 columns and (100 x number
% of points) rows.

X = tall(net(p,4*num_points*2)) ;

% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
%
% Set Up Loop
%
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

% Preallocate the matrix for the row and column indices.

%row_col_ind_mat = zeros(num_points,4) ;

% Preallocate the augmented Sobol matrix.

aug_Sobol_mat = zeros(num_points,5) ;

X0 = gather(X(1:(1+(2*num_points)-1),:)) ;

size_X0 = size(X0)

% For each of the points that are to be selected on the surface, using this
% routine...

additional_row_shift = 0 ;

for point_itr = 1:1:num_points

% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
%
% Create Row and Column Indices
%
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

% The Sobol numbers, which are always between 0 and 1, will be
% multiplied into (number of rows - 1); the ceiling of this number
% will then be taken. This procedure guarantees that, if the number of
% rows is 10 (for example), the returned row index will be no lower
% than 1, and no higher than 9.
%
% The same general procedure will also be carried out to generate the
% column indices.

valid_set_of_indices = 0 ;

while valid_set_of_indices == 0

% Use the first entry in the Sobol row to generate the row index for
% surface 1.

%X0_row_num = point_itr + additional_row_shift

surf_1_row_Sobol = X0( 0 + point_itr + additional_row_shift, 1 );

surf_1_row_ind = ceil(surf_1_row_Sobol * (rows_surf_1_x_mat_num - 1) ) ;

surf_1_row_ind = int32(surf_1_row_ind) ;

% Use the second entry in the Sobol row to generate the column index
% for surface 1.

surf_1_col_Sobol = X0( 0 + point_itr + additional_row_shift, 2 );

surf_1_col_ind = ceil(surf_1_col_Sobol * (cols_surf_1_x_mat_num - 1) ) ;

surf_1_col_ind = int32(surf_1_col_ind) ;

% Use the third entry in the Sobol row to generate the row index for
% surface 2.

surf_2_row_Sobol = X0( 0 + point_itr + additional_row_shift, 3 );

surf_2_row_ind = ceil(surf_2_row_Sobol * (rows_surf_2_x_mat_num - 1) ) ;

surf_2_row_ind = int32(surf_2_row_ind) ;

% Use the fourth entry in the Sobol row to generate the column index
% for surface 2.

surf_2_col_Sobol = X0( 0 + point_itr + additional_row_shift, 4 );

surf_2_col_ind = ceil(surf_2_col_Sobol * (cols_surf_2_x_mat_num - 1) ) ;

surf_2_col_ind = int32(surf_2_col_ind) ;


if [surf_1_row_ind,surf_1_col_ind] == [surf_2_row_ind,surf_2_col_ind]
%disp(' ')
%disp('Differential surfaces 1 and 2 have identical row and column indices.')
additional_row_shift = additional_row_shift + 1 ;
else
valid_set_of_indices = 1 ;

aug_Sobol_mat(point_itr,1) = surf_1_row_Sobol ;

aug_Sobol_mat(point_itr,2) = surf_1_col_Sobol ;

aug_Sobol_mat(point_itr,3) = surf_2_row_Sobol ;

aug_Sobol_mat(point_itr,4) = surf_2_col_Sobol ;

end


end

end

% Set up the probability indices of the augmented Sobol matrix before
% halting.

probability_vec = 0.5 .* ones(num_points,1) ;

probability_vec = probability_vec';

aug_Sobol_mat(:,5) = probability_vec ;

end
