function [emissivity_hyperbolic_toroid,x_hyperbolic_toroid_mat,y_hyperbolic_toroid_mat, z_hyperbolic_toroid_mat, ...
vol_of_hyperbolic_toroid, ...
inner_radius_of_hyperbolic_toroid,outer_radius_of_hyperbolic_toroid, ...
max_z_value_of_hyperbolic_toroid,min_z_value_of_hyperbolic_toroid, ...
max_length_of_z_axis_aligned_square_inside_hyperbolic_toroid, ...
max_square_area,inner_radial_extent_of_max_square,outer_radial_extent_of_max_squar e, ...
max_quadrilateral_area,h_for_max_area_outer_vertex,r_for_max_area_outer_vertex, ...
max_circle_area,r_of_circle_center,max_circle_radius] = ...
...
hyperbolic_toroid_for_Busemann_11(r_inlet,r_throat,l_Busemann_toroid, ...
num_x_points,phi_num_hyperbolic_toroid, ...
emissivity_hyperbolic_toroid, ...
plot_hyperbolic_toroid,plot_hyperbolic_toroid_as_new_figure)
%
% Considwer a Busemann toroid, a pairing of an outer cylinder and an
% inner, converging/diverging surface made from two conical fustrums.
% This surface is generated by rotating a radially offset
% right triangle around the z-axis, and reflecting it around the
% xy-plane.
%
% Now, suppose there is a hyperbola inside that right triangle, which has
% that right triangle's major leg and hypotenuse as its asymptotes. The
% rotation and reflection described above will then generate a hyperbolic
% toroid that resides within the Busemann toroid.
%
% The purpose of this function, then, is to generate the surface of this
% hyperbolic toroid.
%
% Input terms:
%
% r_inlet = ; r_throat = ; l_Busemann_toroid = ;
% num_x_points = ; phi_num_hyperbolic_toroid = ;
% emissivity_hyperbolic_toroid,...
% plot_hyperbolic_toroid = ; plot_hyperbolic_toroid_as_new_figure = ;
%
% where
%
% r_inlet = the radius of the inlet of the Busemann toroid that
% hyperbolic toroid will reside within ;
%
%
% r_throat = the radius of the throat of the Busemann toroid that
% the hyperbolic toroid will reside within ;
%
% l_Busemann_toroid
% = the overall length of the Busemann toroid that the
% hyperbolic toroid will reside within ;
%
% num_x_points
% = the number of x-axis points that will be used in
% the initial creation of the two branches of the 2D
% hyperbola, that will be rotated/reflected to
% generate the 3D hyperbolic toroid ;
%
% phi_num_hyperbolic_toroid
% = the number of azimuthal angles, with respect to the
% z-axis, the 2D hyperbola will be rotated through to
% create the 3D hyperbolic toroid ;
%
% emissivity_hyperbolic_toroid
% = the scaling factor that represents the extent to
% which the hyperbolic toroid resembles a true
% blackbody (in the range from 0 to 1) ;
%
% plot_hyperbolic_toroid
% = the truth value of whether or not the hyperbolic
% toroid should be plotted (1 = yes, 0 = no) ;
%
% and
%
% plot_hyperbolic_toroid_as_new_figure
% = the truth value of whether or not the hyperbolic
% toroid should be plotted as a new figure (1 = yes,
% 0 = no) ;
%
%
% Usage:
%
% [emissivity_hyperbolic_toroid,x_hyperbolic_toroid_mat,y_hyperbolic_toroid_mat, z_hyperbolic_toroid_mat,...
% vol_of_hyperbolic_toroid,...
% inner_radius_of_hyperbolic_toroid,outer_radius_of_hyperbolic_toroid,...
% max_z_value_of_hyperbolic_toroid,min_z_value_of_hyperbolic_toroid,...
% max_length_of_z_axis_aligned_square_inside_hyperbolic_toroid,...
% max_square_area,inner_radial_extent_of_max_square,outer_radial_extent_of_max_squar e,...
% max_quadrilateral_area,h_for_max_area_outer_vertex,r_for_max_area_outer_vertex,...
% max_circle_area,r_of_circle_center,max_circle_radius] = ...
% ...
% hyperbolic_toroid_for_Busemann_11(r_inlet,r_throat,l_Busemann_toroid,...
% num_x_points,phi_num_hyperbolic_toroid,...
% emissivity_hyperbolic_toroid,...
% plot_hyperbolic_toroid,plot_hyperbolic_toroid_as_new_figure) ;

% PROGRAMMING NOTES
%
% 1) The emissivity of the hyperbolic toroid's surface
% has been explicitly added as input.
% The emissivity is directly returned with the meshgrids for the
% corresponding surface. This is being done to facilitate integration
% of the routine's data with the Daun algorithm code.
%
% 2) Additionally, the fliplr commands required for proper function of
% the largest-circle and largest-quadrilateral subroutines are
% reversed after their execution, for the sake of ensuring the
% subsequently generated hyperbolic toroid will plot correctly.
%
% 3) The number_of_dividing_line_points needs to be manually set
% at line 457.
%
% 4) This routine calls the following non-MATLAB subroutines:
%
% hyperbola_in_right_triangle_4
% largest_quadrilateral_in_hyperbolic_toroid
% largest_circle_in_hyperbolic_toroid

% BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
%
% Busemann Toroid's Right Triangle
%
% BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

% Generate the right triangle that defines each "quarter" of the Busemann
% toroid, as seen in its longitudinal cross section.

l_major = l_Busemann_toroid / 2 ;

l_minor = r_inlet - r_throat ;

plot_results = 0 ;

% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
%
% Make and Translate Hyperbola
%
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

% Generate a hyperbola that has the major leg and hypotenuse of that
% right triangle as asymptotes, whose origin-most point is located by two
% complementary (i.e. equally fractionally displaced) points on the right
% triangle.

[x_filtered_vec,y_filtered_vec] = hyperbola_in_right_triangle_4(l_major,l_minor, ...
num_x_points, ...
plot_results) ;

% Split this hyperbola up into two branches, an "upper" branch and a
% "lower" branch. This is being done so that the function can always be
% evaluated in a one-to-one manner.

% Find the point on the hyperbola with the smallest value of x.

[~,min_x_ind] = min(x_filtered_vec) ;

y_at_min_x = y_filtered_vec(1,min_x_ind) ;

% The hyperbola can then be separated into:
% 1) a branch with y-values less than or equal to that of the "smallest
% x" point; and
% 2) a branch with y-values greater than that of the "smallest x" point.
%
% These two branches of the hyperbola will be henceforth referred to as the
% "lower branch" and "upper branch," respectively.

y_lower_ind_vec = find( y_filtered_vec <= y_at_min_x ) ;

x_lower_vec = x_filtered_vec(y_lower_ind_vec) ;

y_lower_vec = y_filtered_vec(y_lower_ind_vec) ;

y_upper_ind_vec = find( y_filtered_vec > y_at_min_x ) ;

x_upper_vec = x_filtered_vec(y_upper_ind_vec) ;

y_upper_vec = y_filtered_vec(y_upper_ind_vec) ;

% Shift the hyperbola so that its largest x-values (i.e. the ones
% coinciding with the minor leg of the Busemann toroid's right triangle)
% lie on the y-axis.

x_lower_vec = x_lower_vec - l_major ;

x_upper_vec = x_upper_vec - l_major ;

% Shift the hyperbola so that its y-axis location corresponds to where it
% would be in a Busemann toroid centered on the x axis. This toroid is
% defined by the right triangle discussed earlier.

y_lower_vec = y_lower_vec - r_inlet ;

y_upper_vec = y_upper_vec - r_inlet ;

% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
%
% Augment Hyperbola
%
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

% The initial translation of these points of the hyperbola will leave a gap
% in between their points that are closest to the y-axis, and the y-axis
% itself. To fill these gaps, a call to pchip must be made; the
% corresponding vectors will then be augmented with these new values.

x_lower_vec_max_x = max(x_lower_vec) ;

x_upper_vec_max_x = max(x_upper_vec) ;

aug_num = 10 ;

% Piecewise spline in a patch for the gap in the lower branch of the
% hyperbola.

x_lower_vec_aug_step = abs( x_lower_vec_max_x - 0 ) / (aug_num-1) ;

x_lower_vec_aug_vec = x_lower_vec_max_x : x_lower_vec_aug_step : 0 ;

x_lower_vec_aug_vec = x_lower_vec_aug_vec(1,2:max(size(x_lower_vec_aug_vec))) ;

%disp(' ')
%disp('Before I chop out duplicated values....')

%disp(' ')
%disp('I chop out duplicated values....')

[x_lower_vec,ia,~] = unique(x_lower_vec) ;

y_lower_vec = y_lower_vec(1,ia) ;

[y_lower_vec_aug_vec] = pchip(x_lower_vec,y_lower_vec,x_lower_vec_aug_vec) ;

x_lower_vec = horzcat(x_lower_vec,x_lower_vec_aug_vec) ;

y_lower_vec = horzcat(y_lower_vec,y_lower_vec_aug_vec) ;

% Piecewise spline in a patch for the gap in the upper branch of the
% hyperbola.

x_upper_vec_aug_step = abs( x_upper_vec_max_x - 0 ) / (aug_num-1) ;

x_upper_vec_aug_vec = x_upper_vec_max_x:x_upper_vec_aug_step:0 ;

x_upper_vec_aug_vec = x_upper_vec_aug_vec(1,2:max(size(x_upper_vec_aug_vec))) ;

%disp(' ')
%disp('I chop out duplicated values....')

[x_upper_vec,ia,~] = unique(x_upper_vec) ;

y_upper_vec = y_upper_vec(1,ia) ;

[y_upper_vec_aug_vec] = pchip(x_upper_vec,y_upper_vec,x_upper_vec_aug_vec) ;

x_upper_vec = horzcat(x_upper_vec,x_upper_vec_aug_vec) ;

y_upper_vec = horzcat(y_upper_vec,y_upper_vec_aug_vec) ;

% The y-axis locations of each point within this cross-section are
% equivalent to the radial displacements of the hyperbolic toroid's points
% within a cylindrical coordinate system, once it is rotated 90 degrees to
% have its central axis coincide with the z-axis. Similarly, the x-axis
% locations of these points correspond to the vertical displacements of the
% toroid's points within that same coordinate system.
%
% To put these transformations in other terms, the
% "upper" branch of the hyperbola becomes the radially "inner" surface of
% the resulting hyperbolic toroid.
%
% By the same token, the "lower" branch of the hyperbola becomes the
% radially "outer" surface of the resulting hyperbolic toroid.

r_outer_vec = abs(y_lower_vec) ;

r_inner_vec = abs(y_upper_vec) ;

h_outer_vec = x_lower_vec ;

h_inner_vec = x_upper_vec ;

phi_vec = 0: (2*pi) / (phi_num_hyperbolic_toroid-1) : 2*pi ;

% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
% OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
%
% Calculate Volume of Hyperbolic Toroid
%
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
% OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

% Augment the outer and inner vectors, so that the two branches of the
% hyperbola will always have height values in common.

h_outer_not_in_inner_vec = setdiff(h_outer_vec,h_inner_vec) ;

r_aug_inner_vec = pchip(h_inner_vec,r_inner_vec,h_outer_not_in_inner_vec) ;

h_inner_vec = horzcat(h_inner_vec,h_outer_not_in_inner_vec) ;

r_inner_vec = horzcat(r_inner_vec,r_aug_inner_vec) ;

[h_inner_vec,sorted_h_inner_vec_ind] = sort(h_inner_vec, 'ascend') ;

r_inner_vec = r_inner_vec(1,sorted_h_inner_vec_ind) ;

h_inner_not_in_outer_vec = setdiff(h_inner_vec,h_outer_vec) ;

r_aug_outer_vec = pchip(h_outer_vec,r_outer_vec,h_inner_not_in_outer_vec) ;

h_outer_vec = horzcat(h_outer_vec,h_inner_not_in_outer_vec) ;

r_outer_vec = horzcat(r_outer_vec,r_aug_outer_vec) ;

[h_outer_vec,sorted_h_outer_vec_ind] = sort(h_outer_vec, 'ascend') ;

r_outer_vec = r_outer_vec(1,sorted_h_outer_vec_ind) ;

% Set up the variables and vectors that will be used to compile data within
% the loop.

volume_of_half_hyperbolic_toroid = 0 ;

radial_difference_vec = zeros(1,max(size(h_inner_vec))) ;

abs_h_displacement_x2_vec = zeros(1,max(size(h_inner_vec))) ;

for h_val_ind = 1:1:max(size(h_inner_vec)) - 1

% Compile the radial differences, and the 2 * z-axis-displacement
% values, for later use.

radial_difference_vec(1,h_val_ind) = r_outer_vec(1,h_val_ind) - r_inner_vec(1,h_val_ind) ;

abs_h_displacement_x2_vec(1,h_val_ind) = 2 * abs(h_inner_vec(1,h_val_ind)) ;

if h_val_ind == max(size(h_inner_vec)) - 1

radial_difference_vec(1,max(size(h_inner_vec))) = r_outer_vec(1,max(size (h_inner_vec))) - r_inner_vec(1,max(size(h_inner_vec))) ;

abs_h_displacement_x2_vec(1,max(size(h_inner_vec))) = 2 * h_inner_vec(1,max(size (h_inner_vec))) ;

else
end

% Find the "differential" volume element of the hyperbolic toroid, by
% finding the difference between the volumes of the outer and inner
% frustums bounding it.

vol_of_outer_frustum = (pi/3) ...
* ( (r_outer_vec(1,h_val_ind)^2) + (r_outer_vec(1,h_val_ind)*r_outer_vec(1, h_val_ind+1)) + (r_outer_vec(1,h_val_ind+1)^2) ) ...
* abs(h_inner_vec(1,h_val_ind)-h_inner_vec(1,h_val_ind+1)) ;

vol_of_inner_frustum = (pi/3) ...
* ( (r_inner_vec(1,h_val_ind)^2) + (r_inner_vec(1,h_val_ind)*r_inner_vec(1, h_val_ind+1)) + (r_inner_vec(1,h_val_ind+1)^2) ) ...
* abs(h_inner_vec(1,h_val_ind)-h_inner_vec(1,h_val_ind+1)) ;

vol_of_annulus = vol_of_outer_frustum - vol_of_inner_frustum ;

volume_of_half_hyperbolic_toroid = volume_of_half_hyperbolic_toroid + vol_of_annulus ;

end

vol_of_hyperbolic_toroid = 2 * volume_of_half_hyperbolic_toroid ;

% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
%
% Largest Square Calculations
%
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

% Use pchip interpolation to estimate the point where the difference
% between the radial extent of a box, and its height (z-axis) extent, is
% zero. This will represent the length of the largest z-axis aligned square
% that can fit in the hyperbolic toroid.

diff_between_radial_extent_and_2x_h_displacement_vec = abs_h_displacement_x2_vec - radial_difference_vec ;

max_length_of_z_axis_aligned_square_inside_hyperbolic_toroid = pchip (diff_between_radial_extent_and_2x_h_displacement_vec,abs_h_displacement_x2_vec,0) ;

% Using the size of the square, determine the inner radial extent of the
% square using pchip. This is done by expressing the inner radii as a
% function of the radial differences, then using pchip to interpolate the
% radial value.

inner_radial_extent_of_max_square = pchip(radial_difference_vec,r_inner_vec, max_length_of_z_axis_aligned_square_inside_hyperbolic_toroid) ;

% Using the size of the square, determine the outer radial extent of the
% square using pchip. This is done by expressing the inner radii as a
% function of the radial differences, then using pchip to interpolate the
% radial value.

outer_radial_extent_of_max_square = pchip(radial_difference_vec,r_outer_vec, max_length_of_z_axis_aligned_square_inside_hyperbolic_toroid) ;

max_square_area = max_length_of_z_axis_aligned_square_inside_hyperbolic_toroid^2 ;

% FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
% QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
%
% Find Largest Quadrilateral And Largest Circle
%
% FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
% QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

% Condition the radial and height vectors for the hyperbola, so that they
% will work properly within the "largest quadrilateral" and "largest
% circle" routines.
%
% As a reminder, the cylindrical coordinates of the toroid relate to the
% Cartesian coordinates of the hyperbola in the following manner....
%
% r = y
% h = x
% inner = upper
% outer = lower

r_inner_vec = -fliplr(r_inner_vec) ;

h_inner_vec = fliplr(h_inner_vec) ;

r_total_hyperbola_vec = horzcat(r_inner_vec,-r_outer_vec) ;

h_total_hyperbola_vec = horzcat(h_inner_vec,h_outer_vec) ;

[max_quadrilateral_area,h_for_max_area_outer_vertex,r_for_max_area_outer_vertex] = ...
largest_quadrilateral_in_hyperbolic_toroid(h_total_hyperbola_vec,r_total_hyperbola _vec) ;

r_for_max_area_outer_vertex = abs(r_for_max_area_outer_vertex) ;

number_of_dividing_line_points = 100 ;

[max_circle_area,r_of_circle_center,max_circle_radius] = ...
largest_circle_in_hyperbolic_toroid(h_total_hyperbola_vec,r_total_hyperbola_vec, number_of_dividing_line_points) ;

r_of_circle_center = abs(r_of_circle_center) ;

% Reverse the previous fliplr commands, so that the hyperbolic toroid
% surface generated in the following step will render properly in surf.

r_inner_vec = -fliplr(r_inner_vec) ;

h_inner_vec = fliplr(h_inner_vec) ;

% GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
%
% Generate Hyperbolic Torus Surface
%
% GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

% Generate a meshgrid to yield the resulting segments of the hyperbolic
% torus.

% lhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlh
%
% --lower half--
%
% lhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlh

% Generate the outer segment of the lower half.

[phi_mat,r_outer_mat] = meshgrid(phi_vec,r_outer_vec) ;

h_outer_vec = h_outer_vec .* (r_outer_vec./r_outer_vec) ;

h_outer_mat = h_outer_vec' .* ones(max(size(r_outer_vec)),max(size(phi_vec))) ;

[x_lh_outer_mat,y_lh_outer_mat,z_lh_outer_mat] = pol2cart(phi_mat,r_outer_mat,h_outer_mat) ;

% Generate the inner segment of the lower half.

[phi_mat,r_inner_mat] = meshgrid(phi_vec,r_inner_vec) ;

h_inner_vec = h_inner_vec .* (r_inner_vec./r_inner_vec) ;

h_inner_mat = h_inner_vec' .* ones(max(size(r_inner_vec)),max(size(phi_vec))) ;

[x_lh_inner_mat,y_lh_inner_mat,z_lh_inner_mat] = pol2cart(phi_mat,r_inner_mat,h_inner_mat) ;

% Merge the meshgrids corresponding to the "inner" and "outer" surfaces of
% the toroid's lower half.

x_lh_inner_2_mat = flipud(x_lh_inner_mat);
y_lh_inner_2_mat = flipud(y_lh_inner_mat);
z_lh_inner_2_mat = flipud(z_lh_inner_mat);

x_lh_inner_outer_mat = vertcat(x_lh_inner_2_mat,x_lh_outer_mat);
y_lh_inner_outer_mat = vertcat(y_lh_inner_2_mat,y_lh_outer_mat);
z_lh_inner_outer_mat = vertcat(z_lh_inner_2_mat,z_lh_outer_mat);

% uhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuh
%
% --upper half--
%
% uhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuh

% Generate the upper half of the toroid by reflection.

x_uh_inner_outer_mat = x_lh_inner_outer_mat ;

y_uh_inner_outer_mat = y_lh_inner_outer_mat ;

z_uh_inner_outer_mat = -z_lh_inner_outer_mat ;

% mthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmth
%
% --merge two halves--
%
% mthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmthmth

% Excise the first row of each "upper half" meshgrid, since this is a set
% of redundant points, along the innermost radius of the toroid, that is
% shared in common with the lower half of the toroid.

[row_num,~] = size(x_uh_inner_outer_mat);

x_uh_inner_outer_mat = x_uh_inner_outer_mat(2:1:row_num,:) ;

y_uh_inner_outer_mat = y_uh_inner_outer_mat(2:1:row_num,:) ;

z_uh_inner_outer_mat = z_uh_inner_outer_mat(2:1:row_num,:) ;

% Reverse the order of the meshgrids for the upper half of the hyperbolic
% toroid. This ensures that, when the two sets of meshgrids are merged, the
% running order of the points will proceed with a counterclockwise
% rotation (i.e. outer-upper-inner-lower-outer), when viewed from the +x
% section of the longitudinally intersecting xz-plane.
%
% NOTE: The radially outermost ring of points on the hyperbolic toroid is
% also duplicated between the upper and lower half meshgrids of the torus.
% However, the corresponding duplicate rows cannot be deleted without
% splitting open the surface of the toroid.

x_uh_inner_outer_mat = flipud(x_uh_inner_outer_mat) ;

y_uh_inner_outer_mat = flipud(y_uh_inner_outer_mat) ;

z_uh_inner_outer_mat = flipud(z_uh_inner_outer_mat) ;

x_hyperbolic_toroid_mat = vertcat(x_uh_inner_outer_mat,x_lh_inner_outer_mat);

y_hyperbolic_toroid_mat = vertcat(y_uh_inner_outer_mat,y_lh_inner_outer_mat);

z_hyperbolic_toroid_mat = vertcat(z_uh_inner_outer_mat,z_lh_inner_outer_mat);

% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
% GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
%
% Return Other Geometric Parameters
%
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
% GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

% Return the outer radius of the hyperbolic toroid.

outer_radius_of_hyperbolic_toroid = max(max(x_hyperbolic_toroid_mat)) ;

% Return the inner radius of the hyperbolic toroid.

radii_squared_mat = (x_hyperbolic_toroid_mat.^2) + (y_hyperbolic_toroid_mat.^2) ;

radii_mat = radii_squared_mat.^0.5 ;

inner_radius_of_hyperbolic_toroid = min(min(radii_mat)) ;

% Return the highest z extent of the hyperbolic toroid.

max_z_value_of_hyperbolic_toroid = max(max(z_hyperbolic_toroid_mat)) ;

% Return the lowest z extent of the hyperbolic toroid.

min_z_value_of_hyperbolic_toroid = min(min(z_hyperbolic_toroid_mat)) ;

% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
%
% Plot Hyperbolic Toroid Surfaces If Asked
%
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
% HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

if plot_hyperbolic_toroid == 1

if plot_hyperbolic_toroid_as_new_figure == 1

figure

surf(x_hyperbolic_toroid_mat,y_hyperbolic_toroid_mat, z_hyperbolic_toroid_mat, 'EdgeColor' ,'none')

hold on
axis equal

xlabel( 'X axis (m)' )
ylabel( 'Y axis (m)' )
zlabel( 'Z axis (m)' )

else

hold on
axis equal

surf(x_hyperbolic_toroid_mat,y_hyperbolic_toroid_mat, z_hyperbolic_toroid_mat, 'EdgeColor' ,'k')

end

if plot_hyperbolic_toroid_as_new_figure == 1

cva = camva ;

camva(0.8*cva);

camva( 'manual')

else
end

else
end

end
Use Right Triangle to Construct Hyperbola
