%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Hiroshima University Ram tube
%Page 107, Ram Accelerators, K. Takayama, A. Sasoh
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Propellant = '1.4CH_4 + 2O_2 + 4.3CO_2' ;
gamma = 1.3302;
freestream_enthalpy = 481.97*1000; % Units J/kg
Sound_Speed = 299.60; %Units m/s
temp = 298; % Units Kelvin %Freestream Temperature
pressure = 0.45; %Units Mpa %Freestream Pressure

vram = 1020; %m/s

Mach_num = vram/Sound_Speed;

area_ratio = Kantrowitz5( Mach_num,gamma );

r_inlet = 1;

r_throat_c_k = r_throat_calc(r_inlet, area_ratio);

r_throat = r_throat_c_k;

ycord_throat = r_inlet - r_throat;

l_Busemann_toroid = 8;

num_r_inlet_cone = 600;
phi_num_inlet = 600;
phi_num_cylinder = 600;
h_num_cylinder = 600;
emissivity_inlet = 1;
emissivity_nozzle = 1;
emissivity_cylinder = 1;
plot_Busemann_toroid = 1;

[diagonal_length_of_leading_cone,diagonal_length_of_frustum,cone_full_angle, ...
emissivity_inlet,x_inlet_mat,y_inlet_mat,z_inlet_mat, ...
emissivity_nozzle,x_nozzle_mat,y_nozzle_mat,z_nozzle_mat, ...
emissivity_cylinder,x_cylinder_mat,y_cylinder_mat,z_cylinder_mat, ...
phi_cylinder_mat] = ...
Busemann_toroid_7(r_inlet,r_throat,l_Busemann_toroid, ...
num_r_inlet_cone,phi_num_inlet, ...
phi_num_cylinder,h_num_cylinder, ...
emissivity_inlet,emissivity_nozzle,emissivity_cylinder, ...
plot_Busemann_toroid) ;

num_x_points= 600;
phi_num_hyperbolic_toroid = 600;
emissivity_hyperbolic_toroid = 1;
plot_hyperbolic_toroid = 1;
plot_hyperbolic_toroid_as_new_figure = 0;

[emissivity_hyperbolic_toroid,x_hyperbolic_toroid_mat,y_hyperbolic_toroid_mat, z_hyperbolic_toroid_mat, ...
vol_of_hyperbolic_toroid, ...
inner_radius_of_hyperbolic_toroid,outer_radius_of_hyperbolic_toroid, ...
max_z_value_of_hyperbolic_toroid,min_z_value_of_hyperbolic_toroid, ...
max_length_of_z_axis_aligned_square_inside_hyperbolic_toroid, ...
max_square_area,inner_radial_extent_of_max_square,outer_radial_extent_of_max_squar e, ...
max_quadrilateral_area,h_for_max_area_outer_vertex,r_for_max_area_outer_vertex, ...
max_circle_area,r_of_circle_center,max_circle_radius] = ...
...
hyperbolic_toroid_for_Busemann_11(r_inlet,r_throat,l_Busemann_toroid, ...
num_x_points,phi_num_hyperbolic_toroid, ...
emissivity_hyperbolic_toroid, ...
plot_hyperbolic_toroid,plot_hyperbolic_toroid_as_new_figure) ;

size_of_cube = 0.1;
number_of_meshgrid_points= 600;
number_of_cubes = 54;
skip_every_nth_box = 0;
cube_orientation = 1;
plot_ring_of_boxes = 1;
plot_ring_of_boxes_as_new_figure = 0;

[x_meshes_for_boxes_3mat,y_meshes_for_boxes_3mat,z_meshes_for_boxes_3mat, ...
inner_radius_of_ring_of_boxes,outer_radius_of_ring_of_boxes] = ...
create_ring_of_boxes_7(size_of_cube,number_of_meshgrid_points,number_of_cubes, ...
skip_every_nth_box,cube_orientation, ...
plot_ring_of_boxes,plot_ring_of_boxes_as_new_figure)

v = axis;
v(1,1) = 0;
axis(v)

surf_1_x_mat = x_nozzle_mat;
surf_1_y_mat = y_nozzle_mat;
surf_1_z_mat = z_nozzle_mat;


surf_2_x_mat = x_cylinder_mat;
surf_2_y_mat = y_cylinder_mat;
surf_2_z_mat = z_cylinder_mat;

obs_surf_x_mat = x_hyperbolic_toroid_mat;
obs_surf_y_mat = y_hyperbolic_toroid_mat;
obs_surf_z_mat = z_hyperbolic_toroid_mat;

n_simulation_runs = 16;
n_point_pairs = 8192*2;
expected_ratio_of_total_point_pairs_to_accepted_point_pairs = 32*2;
contraction_factor_denom =1;

movement_of_ray_relative_to_center_of_surface_1 = +1;
movement_of_ray_relative_to_center_of_surface_2 = +1;
true_val = 0;

[F12_view_factor_vec, ...
is_ray_obstructed_3mat,obstruction_point_3mat, ...
dA1_center_3mat,dA2_center_3mat, ...
n_dA1_normal_3mat,n_dA2_normal_3mat, ...
mag_root_12_valid_3mat, ...
mag_root_12_bogus_3mat, ...
avg_F12,error, ...
std_F12,RSD, ...
number_of_bogus_runs, ...
run_time_in_s, ...
total_valid_point_pairs_assessed, ...
grand_total_point_pairs_assessed] = ...
Monte_Carlo_view_factor_obstructed_fix_par_2(n_simulation_runs,n_point_pairs, ...
expected_ratio_of_total_point_pairs_to_accepted_point_pairs, ...
surf_1_x_mat,surf_1_y_mat,surf_1_z_mat, ...
surf_2_x_mat,surf_2_y_mat,surf_2_z_mat, ...
movement_of_ray_relative_to_center_of_surface_1, ...
movement_of_ray_relative_to_center_of_surface_2, ...
obs_surf_x_mat,obs_surf_y_mat,obs_surf_z_mat, ...
true_val)
