function [max_quadrilateral_area,x_for_max_area_outer_vertex,y_for_max_area_outer_vertex] = ...
largest_quadrilateral_in_hyperbolic_toroid(x_hyperbola_vec,y_hyperbola_vec)
%
% Consider the case of a hyperbolic toroid. This toroid is generated by
% revolution and reflection of a rotated and translated hyperbola in
% cylindrical coordinates. More specifically, the hyperbola that
% generates this toroid will start out with its uppermost and lowermost
% points on the y-axis, and all of its other points will be at negative
% values of both the x and y coordinates.
%
% The question then becomes, "What is the largest-area quadrilateral that
% can fit within a radial cross-section of this toroid?" Since this
% quadrilateral must consist of two reflected copies of the largest
% triangle that can fit within the original hyperboloid, our problem
% simplifies to one of finding the largest-area triangle that can be
% inscribed within the hyperbola.
%
% NOTE:
%
% For this routine to function correctly, the uppermost point must be at
% the beginning of each Cartesian vector: the lowermost point must be at
% teh end of each Cartesian vector.
%
% Usage:
%
% [max_quadrilateral_area,x_for_max_area_outer_vertex,y_for_max_area_outer_vertex] = ...
% largest_quadrilateral_in_hyperbolic_toroid(x_hyperbola_vec,y_hyperbola_vec) ;

% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
%
% Validation
%
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV

if max(size(x_hyperbola_vec)) ~= max(size(y_hyperbola_vec))
error( 'The x and y vectors for the hyperbola must be the same size.' )
else
end

% first_x_hyperbola_vec = x_hyperbola_vec(1,1)

% last_x_hyperbola_vec = x_hyperbola_vec(1,max(size(y_hyperbola_vec)))

% first_y_hyperbola_vec = y_hyperbola_vec(1,1)

% last_y_hyperbola_vec = y_hyperbola_vec(1,max(size(y_hyperbola_vec)))

if y_hyperbola_vec(1,1) <= y_hyperbola_vec(1,max(size(y_hyperbola_vec)))
error( 'The first point on the hyperbola must be above the last point on the hyperbola.' )
else
end

% For each and every point on the hyperbola...

uppermost_point_vec = [x_hyperbola_vec(1,1),y_hyperbola_vec(1,1)] ;

lowermost_point_vec = [x_hyperbola_vec(1,max(size(x_hyperbola_vec))),y_hyperbola_vec(1,max (size(x_hyperbola_vec)))] ;

hyperbola_mat = horzcat(x_hyperbola_vec',y_hyperbola_vec') ;

% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
%
% Make Triangles
%
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

% Let side a be the leg running from the uppermost point of the hyperbola
% to a selected point on the hyperbola.

uppermost_point_mat = uppermost_point_vec .* ones(max(size(x_hyperbola_vec)),2) ;

% size_hyperbola_mat = size(hyperbola_mat)

% size_uppermost_point_mat = size(uppermost_point_mat)

upper_adj_hyperbola_mat = hyperbola_mat-uppermost_point_mat ;

side_a_vec = magnitude( upper_adj_hyperbola_mat ) ;

% Let side b be the leg running from a selected point on the hyperbola to
% the lowermost point on the hyperbola.

%side_b_vec = magnitude( hyperbola_mat(:,:) - lowermost_point_vec )

%side_b_vec = magnitude( hyperbola_mat - (lowermost_point_vec.*ones(max(size (x_hyperbola_vec)),2)) )

lowermost_point_mat = lowermost_point_vec .* ones(max(size(x_hyperbola_vec)),2) ;

lower_adj_hyperbola_mat = hyperbola_mat-lowermost_point_mat ;

side_b_vec = magnitude( lower_adj_hyperbola_mat ) ;

% Let side c be the leg running from the uppermost point on the hyperbola
% to the lowermost point on the hyperbola.

side_c_vec = ( uppermost_point_vec(1,2) - lowermost_point_vec(1,2) ) .* ones(max(size (x_hyperbola_vec)),1) ;

% FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
%
% Find Areas
%
% FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

% Calculate the semiperimeters.

semiperimeter_vec = 0.5 * ( side_a_vec + side_b_vec + side_c_vec ) ;

% Use Heron's formula to calculate the area of the corresponding triangle.

area_vec = sqrt( semiperimeter_vec .* (semiperimeter_vec-side_a_vec) .* (semiperimeter_vecside_ b_vec) .* (semiperimeter_vec-side_c_vec) ) ;

area_vec = 2.*area_vec ;

% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
%
% Return Maximum Area Quadrilateral
%
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ

[max_quadrilateral_area,ind_max_area] = max(area_vec) ;

x_for_max_area_outer_vertex = x_hyperbola_vec(1,ind_max_area) ;

y_for_max_area_outer_vertex = y_hyperbola_vec(1,ind_max_area) ;

end
