function [max_circle_area,y_of_circle_center,max_circle_radius] = ...
largest_circle_in_hyperbolic_toroid(x_hyperbola_vec,y_hyperbola_vec, number_of_dividing_line_points)
%
% Consider the case of a hyperbolic toroid. This toroid is generated by
% revolution and reflection of a rotated and translated hyperbola in
% cylindrical coordinates. More specifically, the hyperbola that
% generates this toroid will start out with its uppermost and lowermost
% points on the y-axis, and all of its other points will be at negative
% values of both the x and y coordinates.
%
% The question then becomes, "What is the largest-area circle that
% can fit within a radial cross-section of this toroid?"
%
% NOTE:
%
% For this routine to function correctly, the uppermost point of the
% hyperbola must be at the beginning of each Cartesian vector: the
% lowermost point of the hyperbola must be at the end of each Cartesian
% vector.
%
% Usage:
%
% [max_circle_area,y_of_circle_center,max_circle_radius] = ...
% largest_circle_in_hyperbolic_toroid(x_hyperbola_vec,y_hyperbola_vec, number_of_dividing_line_points) ;
%

% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
%
% Validation
%
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV

if max(size(x_hyperbola_vec)) ~= max(size(y_hyperbola_vec))
error( 'The x and y vectors for the hyperbola must be the same size.' )
else
end

if number_of_dividing_line_points <= 0
error( 'The number of dividing line points must be a positive, nonzero number.' )
else
if mod(number_of_dividing_line_points,1) > 0
error( 'The number of dividing line points must be a positive integer.' )
else
end
end

if y_hyperbola_vec(1,1) <= y_hyperbola_vec(1,max(size(y_hyperbola_vec)))
error( 'The first point on the hyperbola must be above the last point on the hyperbola.' )
else
end

% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
%
% Setup
%
% SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

% For each and every point on the hyperbola...

uppermost_point_vec = [x_hyperbola_vec(1,1),y_hyperbola_vec(1,1)] ;

lowermost_point_vec = [x_hyperbola_vec(1,max(size(x_hyperbola_vec))),y_hyperbola_vec(1,max (size(x_hyperbola_vec)))] ;

hyperbola_mat = horzcat(x_hyperbola_vec',y_hyperbola_vec') ;

% Create a line running from the uppermost point on the hyperbola to the
% lowest point.

y_dividing_line_vec = uppermost_point_vec(1,2) : (lowermost_point_vec(1,2)- uppermost_point_vec(1,2))/(number_of_dividing_line_points-1) : lowermost_point_vec(1,2) ;

dividing_line_mat = horzcat(zeros(number_of_dividing_line_points,1),y_dividing_line_vec') ;

radii_mat = zeros(number_of_dividing_line_points,max(size(x_hyperbola_vec))) ;

% For each point on the dividing_line...

for dividing_line_itr = 1:1:number_of_dividing_line_points
% Find the distance between the dividing line point and each point on
% the hyperbola. These represent the radii of all circles that can be
% drawn from the dividing line point, which are also either tangent to,
% or intersecting,the hyperbola.

dividing_line_working_mat = dividing_line_mat(dividing_line_itr,:) .* ones(max(size (x_hyperbola_vec)),2) ;

adj_hyperbola_mat = hyperbola_mat-dividing_line_working_mat ;

size_adj_hyperbola_mat = size(magnitude_for_matrices(adj_hyperbola_mat))

radii_mat(dividing_line_itr,:) = ( magnitude_for_matrices(adj_hyperbola_mat) )' ;

end

%radii_mat = radii_mat ;

% Find the minimum radius for each dividing line point. This will represent
% the largest circle that can fit within the hyperbola at each dividing
% line point.

min_radii_vec = min(radii_mat,[],2) ;

% For all of these radii, find the largest one. This will represent the
% largest circle, centered on the dividing line, that can fit in the
% hyperbola.

[max_circle_radius,ind_of_max_radius] = max(min_radii_vec) ;

max_circle_area = pi*(max_circle_radius^2) ;

y_of_circle_center = y_dividing_line_vec(1,ind_of_max_radius) ;

end
