function [F12_view_factor_vec, ...
dA1_center_3mat,dA2_center_3mat, ...
n_dA1_normal_3mat,n_dA2_normal_3mat, ...
aug_Sobol_mat, ...
mag_root_12_valid_3mat, ...
mag_root_12_bogus_3mat, ...
avg_F12,error, ...
std_F12,RSD] = ...
Monte_Carlo_view_factor_27(n_simulation_runs,n_point_pairs, ...
surf_1_x_mat,surf_1_y_mat,surf_1_z_mat, ...
surf_2_x_mat,surf_2_y_mat,surf_2_z_mat, ...
movement_of_ray_relative_to_center_of_surface_1, ...
movement_of_ray_relative_to_center_of_surface_2, ...
true_val)
%
% The purpose of this function is to calculate the view factors between
% two finite surfaces, using the Monte Carlo method. It assumes that
% these two surfaces are unobstructed by any other surface or object.
%
%
% Input terms:
%
% n_simulation_runs = the number of rounds of Monte Carlo
% approximation that are to be done in this run
% of the routine;
%
% n_point_pairs = the number of pairs of points that are to be
% chosen on surface 1 and surface 2, within each
% Monte Carlo run;
%
% surf_1_x_mat = ; surf_1_y_mat = ; surf_1_z_mat = ;
%
% where these are meshgrids representing surface 1 in Cartesian
% coordinates.
%
% surf_2_x_mat = ; surf_2_y_mat = ; surf_2_z_mat = ;
%
% where these are meshgrids representing surface 2 in Cartesian
% coordinates.
%
% movement_of_ray_relative_to_center_of_surface_1
%
% = one of three possible values...
%
% +1 iff rays are emitted out and away from
% the center of surface 1 (as in the case
% of rays streaming away from the outer
% surface of a hot sphere);
%
% -1 iff rays are moving into and toward the
% center of surface 1 (as in the case
% of rays streaming in toward the center
% of a hot spherical cavity);
%
% 0 iff the "sense" of the emitted
% radiation coming from surface 1 is
% deemed unimportant, by the user, to the
% geometry being considered (as in the
% case of an LED panel emitting light in
% all directions forward of its front
% face).
%
%
% movement_of_ray_relative_to_center_of_surface_2
%
% = one of three possible values...
%
% +1 iff incoming rays must move out and
% away from the center of surface 2 (as
% in the case of rays streaming toward
% the inner surface of an integrating sphere);
%
% -1 iff rays are moving into and toward the
% center of surface 2 (as in the case
% of rays streaming toward the center
% of a hemispherical insolation sensor);
%
% 0 iff the "sense" of the emitted
% radiation coming toward surface 2 is
% deemed unimportant, by the user, to the
% geometry being considered (as in the
% case of a flat solar cell receiving
% radiated energy from all directions in
% front of its receiving face).
%
%
% Output terms:
%
% F12_view_factor_vec = a vector containing all of the physically
% reasonable values of F12 (i.e. F12 <= 1)
% generated by the Monte Carlo runs;
%
% dA1_center_3mat = a 3-dimensional matrix whose rows are
% the Cartesian (x,y,z) vectors locating
% the center-points of quadrilaterals on
% surface 1, and whose pages correspond to
% each individual cycle of the Monte Carlo
% run;
%
% dA2_center_3mat = a 3-dimensional matrix whose rows are
% the Cartesian (x,y,z) vectors locating
% the center-points of quadrilaterals on
% surface 2, and whose pages correspond to
% each individual cycle of the Monte Carlo
% run;
%
% n_dA1_normal_3mat = a 3-dimensional matrix whose rows are
% Cartesian (x,y,z) coordinates
% describing the extents of the normal
% vectors located at the centers of the
% quadrilaterals on surface 1, and whose
% pages correspond to each individual cycle
% of the Monte Carlo run;
%
% n_dA2_normal_3mat = a 3-dimensional matrix whose rows are
% Cartesian (x,y,z) coordinates
% describing the extents of the normal
% vectors located at the centers of the
% quadrilaterals on surface 2, and whose
% pages correspond to each individual cycle
% of the Monte Carlo run;
%
% aug_Sobol_mat = a 2-dimensional matrix where each row
% contains a vector within the 4-dimensional
% Sobol set, along with a probability term
% weighting its future choice by a Monte
% Carlo routine;
%
% mag_root_12_valid_3mat = a 3-dimensional matrix whose rows (and 1
% column) represent the r12 values assocated
% with individual point pairs generated
% during a valid (i.e. F12 <= 1) Monte Carlo
% cycle, and whose pages represent the
% simulation run over which that combination
% of r12 values occured;
%
% mag_root_12_bogus_3mat = a 3-dimensional matrix whose rows (and 1
% column) represent the r12 values assocated
% with individual point pairs generated
% during a bogus (i.e. F12 > 1) Monte Carlo
% cycle, and whose pages represent the
% simulation run over which that combination
% of r12 values occured;
%
% avg_F12 = the average value of F12 observed over all
% cycles of the Monte Carlo run;
%
% error = the percent error of the average value of
% F12, in comparison with the known value of
% F12;
%
% std_F12 = the absolute standard deviation (unitless)
% of the values of F12 obtained by the Monte
% Carlo runs;
%
% and
%
% RSD = the relative standard deviation (in
% percent) of the values of F12 obtained by
% the Monte Carlo runs.
%
% Usage:
%
% [F12_view_factor_vec,...
% dA1_center_3mat,dA2_center_3mat,...
% n_dA1_normal_3mat,n_dA2_normal_3mat,...
% aug_Sobol_mat,...
% mag_root_12_valid_3mat,...
% mag_root_12_bogus_3mat,...
% avg_F12,error,...
% std_F12,RSD] =...
% Monte_Carlo_view_factor_27(n_simulation_runs,n_point_pairs,...
% surf_1_x_mat,surf_1_y_mat,surf_1_z_mat,...
% surf_2_x_mat,surf_2_y_mat,surf_2_z_mat,...
% movement_of_ray_relative_to_center_of_surface_1,...
% movement_of_ray_relative_to_center_of_surface_2,...
% true_val);

% PROGRAMMING NOTES
%
% 1) This routine differs from its predecessor,
% Monte_Carlo_view_factor_26, in that its Sobol matrix generating
% subroutine has been altered to make more-efficient use of memory.
%
% 2) This function makes use of the following non-MATLAB subroutines:
% surf_to_area
% aug_sobol_select_8
% quadrilateral_pairs_select
% diff_view_factor_8
% Sobol_learning_system_3
%

% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
%
% Validation
%
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV

if n_simulation_runs <= 0
error( 'The number of simulation runs must be a positive, nonzero number.' )
else
if mod(n_simulation_runs,1) > 0
error( 'The number of simulation runs must be an integer.' )
else
end
end

if n_point_pairs <= 0
error( 'The number of point pairs must be a positive, nonzero number.' )
else
if mod(n_point_pairs,1) > 0
error( 'The number of point pairs must be an integer.' )
else
end
end

% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
%
% Initialize Monte Carlo Runs
%
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

disp( ' ')

tic

t = now ;

disp( 'Run started at...' )
d = datetime(t, 'ConvertFrom' ,'datenum' )
disp( ' ')

% Initialize the 3D matrices for storing the points and vectors of each
% individual run.

dA1_center_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

dA2_center_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

n_dA1_normal_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

n_dA2_normal_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

mag_root_12_valid_3mat = zeros(n_point_pairs,1,n_simulation_runs) ;

%pages_in_bogus_3mat_num = max([n_simulation_runs,ceil(36.069*exp(0.0425*n_point_pairs))]) ;

pages_in_bogus_3mat_num = 100 * n_simulation_runs ;

mag_root_12_bogus_3mat = zeros(n_point_pairs,1,pages_in_bogus_3mat_num) ;

% Calculate the area of surface 2.

% surf_2_area =
[surf_2_area] = surf_to_area(surf_2_x_mat,surf_2_y_mat,surf_2_z_mat) ;

surf_1_center_vec = [mean(mean(surf_1_x_mat)),mean(mean(surf_1_y_mat)),mean(mean (surf_1_z_mat))] ;

surf_2_center_vec = [mean(mean(surf_2_x_mat)),mean(mean(surf_2_y_mat)),mean(mean (surf_2_z_mat))] ;

% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
%
% Monte Carlo Loop
%
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

% For each round of calculation of the view factor...

F12_view_factor_vec = zeros(1,n_simulation_runs) ;

n_rept = ceil(n_simulation_runs/10) ;

number_of_valid_runs = 0 ;

number_of_bogus_runs = 0 ;

% Set up the parameters determining the numbver of rows required for the
% Sobol matrix.

expected_ratio_of_total_points_to_accepted_points = 20

%expected_ratio_of_total_runs_to_valid_runs = 22.2 * ( 10.86 * ( abs (n_point_pairs-128) / 128) )

expected_ratio_of_total_runs_to_valid_runs = 241

contraction_factor_denom = 1 ;

Sobol_matrix_row_num = ceil( ( n_point_pairs * expected_ratio_of_total_points_to_accepted_points ) * ( n_simulation_runs * expected_ratio_of_total_runs_to_valid_runs ) * ( 1 / contraction_factor_denom ) )

Sobol_matrix_row_num = int32(Sobol_matrix_row_num) ;

%Sobol_matrix_row_num = 51200 ;

% Determine the size of the surface 1 x matrix.

[rows_surf_1_x_mat_num,cols_surf_1_x_mat_num] = size(surf_1_x_mat) ;

% rows_surf_1_x_mat_num = int32(rows_surf_1_x_mat_num) ;
%
% cols_surf_1_x_mat_num = int32(cols_surf_1_x_mat_num) ;

% Determine the size of the surface 2 x matrix.

[rows_surf_2_x_mat_num,cols_surf_2_x_mat_num] = size(surf_2_x_mat) ;

% rows_surf_2_x_mat_num = int32(rows_surf_2_x_mat_num) ;
%
% cols_surf_2_x_mat_num = int32(cols_surf_2_x_mat_num) ;

% Generate all the quadrilaterals for all Monte Carlo cycles
% using a Sobol selection subroutine.

[aug_Sobol_mat]= ...
aug_sobol_select_8(rows_surf_1_x_mat_num,cols_surf_1_x_mat_num, ...
rows_surf_2_x_mat_num,cols_surf_2_x_mat_num, ...
Sobol_matrix_row_num) ;

whos

Sobol_select_itr = 0 ;

number_of_passes_through_Sobol_matrix = 0 ;

for simulation_itr = 1:1:n_simulation_runs

is_view_factor_valid = 0 ;

while is_view_factor_valid == 0

sum_of_diff_view_factors = 0 ;

valid_point_pairs_num = 0 ;

% For each iteration across point pairs...

%while valid_point_pairs_num <= n_point_pairs
for point_pair_itr = 1:1:n_point_pairs

% Loop back to the beginning of the Sobol matrix if its end has
% been reached.

if Sobol_select_itr == Sobol_matrix_row_num
Sobol_select_itr = 1 ;
number_of_passes_through_Sobol_matrix = number_of_passes_through_Sobol_matrix + 1
else
Sobol_select_itr = Sobol_select_itr + 1;
% if mod(Sobol_select_itr,1000)==0
% Sobol_select_itr = Sobol_select_itr
% else
% end
end

% Select a point pair probabilistically.

point_pair_selected = 0 ;

point_pair_search_itr = 0 ;

while point_pair_selected == 0

rand_num = rand() ;

if aug_Sobol_mat(Sobol_select_itr,5) >= rand_num
point_pair_selected = 1 ;
else

point_pair_search_itr = point_pair_search_itr + 1 ;

% Halt iteration, and force selection of the current
% point pair, if 100 cycles have elapsed without a
% point-pair selection.

if point_pair_search_itr >= 100
disp( ' ')
disp( 'Point pair search halted after 100 cycles.' )
point_pair_selected = 1 ;
else

% Loop back to the beginning of the Sobol matrix if its end has
% been reached.

if Sobol_select_itr == Sobol_matrix_row_num
Sobol_select_itr = 1 ;
number_of_passes_through_Sobol_matrix = number_of_passes_through_Sobol_matrix + 1
else
Sobol_select_itr = Sobol_select_itr + 1;

% if mod(Sobol_select_itr,1000)==0
% Sobol_select_itr = Sobol_select_itr
% else
% end

end

end

end

end

% EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
%
% Extract Indices
%
% EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

% Extract the indices corresponding to the selected row of the
% Sobol matrix.

surf_1_row_Sobol = aug_Sobol_mat(Sobol_select_itr,1) ;

surf_1_row_ind = ceil(surf_1_row_Sobol * (rows_surf_1_x_mat_num - 1) ) ;

surf_1_row_ind = int32(surf_1_row_ind) ;


surf_1_col_Sobol = aug_Sobol_mat(Sobol_select_itr,2) ;

surf_1_col_ind = ceil(surf_1_col_Sobol * (cols_surf_1_x_mat_num - 1) ) ;

surf_1_col_ind = int32(surf_1_col_ind) ;


surf_2_row_Sobol = aug_Sobol_mat(Sobol_select_itr,3) ;

surf_2_row_ind = ceil(surf_2_row_Sobol * (rows_surf_2_x_mat_num - 1) ) ;

surf_2_row_ind = int32(surf_2_row_ind) ;


surf_2_col_Sobol = aug_Sobol_mat(Sobol_select_itr,4) ;

surf_2_col_ind = ceil(surf_1_col_Sobol * (cols_surf_2_x_mat_num - 1) ) ;

surf_2_col_ind = int32(surf_1_col_ind) ;

% GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
% QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
%
% Generate Quadrilaterals
%
% GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
% QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ

% Call a subroutine to obtain the pair of quadrilaterals that
% corresponds to the preceding indices.

[surf_1_a_vec,surf_1_b_vec,surf_1_c_vec,surf_1_d_vec, ...
surf_2_a_vec,surf_2_b_vec,surf_2_c_vec,surf_2_d_vec] = ...
quadrilateral_pairs_select(surf_1_x_mat,surf_1_y_mat,surf_1_z_mat, ...
surf_2_x_mat,surf_2_y_mat,surf_2_z_mat, ...
[surf_1_row_ind,surf_1_col_ind,surf_2_row_ind,surf_2_col_ind]) ;

% Feed these two inputs to the differential view factor subroutine.

dA1_mat = vertcat(surf_1_a_vec,surf_1_b_vec,surf_1_c_vec,surf_1_d_vec) ;

dA2_mat = vertcat(surf_2_a_vec,surf_2_b_vec,surf_2_c_vec,surf_2_d_vec) ;

[is_point_valid, ...
diff_view_factor_val, ...
n_dA1_normal_vec,n_dA2_normal_vec, ...
mag_root_12] = ...
diff_view_factor_8(dA1_mat,dA2_mat, ...
surf_1_center_vec, ...
movement_of_ray_relative_to_center_of_surface_1, ...
surf_2_center_vec, ...
movement_of_ray_relative_to_center_of_surface_2) ;

% If the resulting differential view factor corresponds to a
% physically valid combination of point pairs...

if is_point_valid == 1

% ...reset this point pair's probability to the negative of
% its original value, so it cannot be selected again by the
% routine.

aug_Sobol_mat(Sobol_select_itr,5) = -aug_Sobol_mat(Sobol_select_itr,5) ;

[aug_Sobol_mat] = Sobol_learning_system_3(aug_Sobol_mat,Sobol_select_itr, is_point_valid) ;

valid_point_pairs_num = valid_point_pairs_num + is_point_valid ;

% Store the information about the center points of each
% differential surface, and their corresponding normals.

dA1_center_vec = mean(dA1_mat,1) ;

dA2_center_vec = mean(dA2_mat,1) ;

dA1_center_3mat(point_pair_itr,:,simulation_itr) = dA1_center_vec ;

dA2_center_3mat(point_pair_itr,:,simulation_itr) = dA2_center_vec ;

n_dA1_normal_3mat(point_pair_itr,:,simulation_itr) = n_dA1_normal_vec ;

n_dA2_normal_3mat(point_pair_itr,:,simulation_itr) = n_dA2_normal_vec ;

mag_root_12_valid_3mat(point_pair_itr,1,simulation_itr) = mag_root_12 ;

% Add the resulting output to the growing sum of differential view
% factor contributions.

sum_of_diff_view_factors = sum_of_diff_view_factors + diff_view_factor_val ;

else

% Reset the probability of this physically invalid point to
% zero, so it cannot be selected again by the routine.

aug_Sobol_mat(Sobol_select_itr,5) = 0 ;

[aug_Sobol_mat] = Sobol_learning_system_3(aug_Sobol_mat,Sobol_select_itr, is_point_valid);

end

end

F12_view_factor_value = ( surf_2_area / valid_point_pairs_num ) * sum_of_diff_view_factors

% If the view factor thus obtained is physically realistic...

if F12_view_factor_value <= 1
% ...keep the value, and increment the number of valid runs by
% one.
is_view_factor_valid = 1 ;

number_of_valid_runs = number_of_valid_runs + 1

F12_view_factor_vec(1,simulation_itr) = F12_view_factor_value ;

% Otherwise...
else
% ...increment the number of bogus runs by 1, and save the
% associated r12 lengths.

number_of_bogus_runs = number_of_bogus_runs + 1 ;

mag_root_12_bogus_3mat(:,:,number_of_bogus_runs) = mag_root_12_valid_3mat (point_pair_itr,1,simulation_itr) ;

% Periodically update the user on the number of bogus runs that
% has been generated.

if mod(number_of_bogus_runs,10) == 0
number_of_bogus_runs = number_of_bogus_runs
else
end

end

end

% Periodically update the user on the status of the calculation.

if mod(simulation_itr,n_rept) == 0
percent_done = 100*simulation_itr/n_simulation_runs ;
formatSpec = 'Run is %4.2f percent done.' ;
disp( ' ')
fprintf(formatSpec,percent_done)
disp( ' ')
else
end

%Sobol_select_itr = Sobol_select_itr

%Sobol_matrix_row_num = Sobol_matrix_row_num

end

disp( ' ')

toc

% Take the absolute value of the probabilities in the augmented Sobol
% matrix, so that the physically reasonable points are made available for
% use by subsequent library-using Monte Carlo codes.

%aug_Sobol_mat(:,5) = abs(aug_Sobol_mat(:,5)) ;

% Output the relevant data from the Monte Carlo run that has just been
% completed.

figure
histogram(aug_Sobol_mat(:,5))

number_of_valid_runs = number_of_valid_runs

number_of_bogus_runs = number_of_bogus_runs

avg_F12 = mean(F12_view_factor_vec)
error = 100*abs(avg_F12-true_val)/true_val
std_F12 = std(F12_view_factor_vec)
RSD = 100*(std_F12/avg_F12)

end
