function [F12_view_factor_vec, ...
is_ray_obstructed_3mat,obstruction_point_3mat, ...
dA1_center_3mat,dA2_center_3mat, ...
n_dA1_normal_3mat,n_dA2_normal_3mat, ...
mag_root_12_valid_3mat, ...
mag_root_12_bogus_3mat, ...
avg_F12,error, ...
std_F12,RSD, ...
number_of_bogus_runs, ...
run_time_in_s, ...
total_valid_point_pairs_assessed, ...
grand_total_point_pairs_assessed] = ...
Monte_Carlo_view_factor_obstructed_fix_par_2(n_simulation_runs,n_point_pairs, ...
expected_ratio_of_total_point_pairs_to_accepted_point_pairs, ...
surf_1_x_mat,surf_1_y_mat,surf_1_z_mat, ...
surf_2_x_mat,surf_2_y_mat,surf_2_z_mat, ...
movement_of_ray_relative_to_center_of_surface_1, ...
movement_of_ray_relative_to_center_of_surface_2, ...
obs_surf_x_mat,obs_surf_y_mat,obs_surf_z_mat, ...
true_val)
%
% The purpose of this function is to calculate the view function between
% two finite surfaces, using the Monte Carlo method. It assumes that
% these two surfaces are obstructed by one other surface or object.
%
% Input terms:
%
% n_simulation_runs = the number of rounds of Monte Carlo
% approximation that are to be done in this run
% of the routine;
%
% n_point_pairs = the number of pairs of points that are to be
% chosen on surface 1 and surface 2, within each
% Monte Carlo run;
%
% expected_ratio_of_total_point_pairs_to_accepted_point_pairs
%
% = the ratio of the grand total of point pairs the
% routine is anticipated to assess, divided by
% the total of geometrically and
% thermodynamically valid point pairs the routine
% is expected to return via the valid Monte Carlo
% runs;
%
% surf_1_x_mat = ; surf_1_y_mat = ; surf_1_z_mat = ;
%
% where these are meshgrids representing surface 1 in Cartesian
% coordinates.
%
% surf_2_x_mat = ; surf_2_y_mat = ; surf_2_z_mat = ;
%
% where these are meshgrids representing surface 2 in Cartesian
% coordinates;
%
% surf_obs_x_mat = ; surf_obs_y_mat = ; surf_obs_z_mat = ;
%
% where these are meshgrids representing the obstructing surface in
% Cartesian coordinates;
%
% movement_of_ray_relative_to_center_of_surface_1
%
% = one of three possible values...
%
% +1 iff rays are emitted out and away from
% the center of surface 1 (as in the case
% of rays streaming away from the outer
% surface of a hot sphere);
%
% -1 iff rays are moving into and toward the
% center of surface 1 (as in the case
% of rays streaming in toward the center
% of a hot spherical cavity);
%
% 0 iff the "sense" of the emitted
% radiation coming from surface 1 is
% deemed unimportant, by the user, to the
% geometry being considered (as in the
% case of an LED panel emitting light in
% all directions forward of its front
% face).
%
% movement_of_ray_relative_to_center_of_surface_2
%
% = one of three possible values...
%
% +1 iff incoming rays must move out and
% away from the center of surface 2 (as
% in the case of rays streaming toward
% the inner surface of an integrating sphere);
%
% -1 iff rays are moving into and toward the
% center of surface 2 (as in the case
% of rays streaming toward the center
% of a hemispherical insolation sensor);
%
% 0 iff the "sense" of the emitted
% radiation coming toward surface 2 is
% deemed unimportant, by the user, to the
% geometry being considered (as in the
% case of a flat solar cell receiving
% radiated energy from all directions in
% front of its receiving face).
%
% Output terms:
%
% F12_view_factor_vec = a vector containing all of the physically
% reasonable values of F12 (i.e. F12 <= 1)
% generated by the Monte Carlo runs;
%
% is_ray_obstructed_3mat = the truth values of whether a ray
% travelling between the two differential
% surfaces of a given geometrically valid
% point pair, in a given Monte
% Carlo run, is blocked by the obstructing
% surface;
%
% obstruction_point_3mat = the Cartesian coordinates of where a given
% obstructed ray is blocked by the
% obstructing surface;
%
% dA1_center_3mat = a 3-dimensional matrix whose rows are
% the Cartesian (x,y,z) vectors locating
% the center-points of quadrilaterals on
% surface 1, and whose pages correspond to
% each individual cycle of the Monte Carlo
% run;
%
% dA2_center_3mat = a 3-dimensional matrix whose rows are
% the Cartesian (x,y,z) vectors locating
% the center-points of quadrilaterals on
% surface 2, and whose pages correspond to
% each individual cycle of the Monte Carlo
% run;
%
% n_dA1_normal_3mat = a 3-dimensional matrix whose rows are
% Cartesian (x,y,z) coordinates
% describing the extents of the normal
% vectors located at the centers of the
% quadrilaterals on surface 1, and whose
% pages correspond to each individual cycle
% of the Monte Carlo run;
%
% n_dA2_normal_3mat = a 3-dimensional matrix whose rows are
% Cartesian (x,y,z) coordinates
% describing the extents of the normal
% vectors located at the centers of the
% quadrilaterals on surface 2, and whose
% pages correspond to each individual cycle
% of the Monte Carlo run;
%
% aug_Sobol_mat = a 2-dimensional matrix where each row
% contains a vector within the 4-dimensional
% Sobol set, along with a probability term
% weighting its future choice by a Monte
% Carlo routine;
%
% mag_root_12_valid_3mat = a 3-dimensional matrix whose rows (and 1
% column) represent the r12 values associated
% with individual point pairs generated
% during a valid (i.e. F12 <= 1) Monte Carlo
% cycle, and whose pages represent the
% simulation run over which that combination
% of r12 values occurred;
%
% mag_root_12_bogus_3mat = a 3-dimensional matrix whose rows (and 1
% column) represent the r12 values associated
% with individual point pairs generated
% during a bogus (i.e. F12 > 1) Monte Carlo
% cycle, and whose pages represent the
% simulation run over which that combination
% of r12 values occurred;
%
% avg_F12 = the average value of F12 observed over all
% cycles of the Monte Carlo run;
%
% error = the percent error of the average value of
% F12, in comparison with the known value of
% F12;
%
% std_F12 = the absolute standard deviation (unitless)
% of the values of F12 obtained by the Monte
% Carlo runs;
%
% and
%
% RSD = the relative standard deviation (in
% percent) of the values of F12 obtained by
% the Monte Carlo runs.
% Usage:
%
% [F12_view_factor_vec,...
% is_ray_obstructed_3mat,obstruction_point_3mat,...
% dA1_center_3mat,dA2_center_3mat,...
% n_dA1_normal_3mat,n_dA2_normal_3mat,...
% mag_root_12_valid_3mat,...
% mag_root_12_bogus_3mat,...
% avg_F12,error,...
% std_F12,RSD,...
% number_of_bogus_runs,...
% run_time_in_s,...
% total_valid_point_pairs_assessed,...
% grand_total_point_pairs_assessed] =...
% Monte_Carlo_view_factor_obstructed_fix_par_2(n_simulation_runs,n_point_pairs,...
% expected_ratio_of_total_point_pairs_to_accepted_point_pairs,...
% surf_1_x_mat,surf_1_y_mat,surf_1_z_mat,...
% surf_2_x_mat,surf_2_y_mat,surf_2_z_mat,...
% movement_of_ray_relative_to_center_of_surface_1,...
% movement_of_ray_relative_to_center_of_surface_2,...
% obs_surf_x_mat,obs_surf_y_mat,obs_surf_z_mat,...
% true_val) ;

% PROGRAMMING NOTES
%
% 1) This code is restructured to enable parallel execution via parfor.
% This is accomplished through the following approaches:
%
% a) The Sobol matrix is still generated outside the loop in its
% entirety. Within the loop, Sobol_select_itr can no longer be passed
% from cycle to cycle as a monotonically-increasing indexing
% variable. (In parallel, each cycle will be executed on a separate
% worker core, with no guarantee that any one cycle will be
% sequential with any preceding or following cycle.). For this
% reason, the Sobol matrix will be executed in blocks that are
% indexed directly by the cycle number.
%
% This is accomplished by:
%
% i) requiring that the size of the Sobol matrix be an integer
% multiple of the number of point pairs;
%
% ii) removing the contraction-factor denominator as a
% user-settable parameter; and
%
% iii) setting the contraction-factor denominator to 1 within the
% code.
%
% b) Information generated by a given cycle will be passed to the
% output vectors and matrices in a cycle-by-cycle, indexed fashion,
% as opposed to the sequential, in-place updating scheme employed by
% "obs_3."
%
% 2) This function makes direct use of the following non-MATLAB
% subroutines:
%
% surf_to_area
% probabilistic_n_point_pairs_select_w_obstruction_3
% aug_sobol_select_8
%
% 3) This function makes indirect use of the following non-MATLAB
% subroutines:
%
% quadrilateral_pairs_select
% diff_view_factor_8
% Sobol_learning_system_3
% double_check_if_ray_obstructed
% is_ray_obstructed_by_surface_4

% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
%
% Validation
%
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV

if n_simulation_runs <= 0
error( 'The number of simulation runs must be a positive, nonzero number.' )
else
if mod(n_simulation_runs,1) > 0
error( 'The number of simulation runs must be an integer.' )
else
end
end

if n_point_pairs <= 0
error( 'The number of point pairs must be a positive, nonzero number.' )
else
if mod(n_point_pairs,1) > 0
error( 'The number of point pairs must be an integer.' )
else
end
end

if expected_ratio_of_total_point_pairs_to_accepted_point_pairs <= 0
error( 'The number of point pairs must be a positive, nonzero number.' )
else
if mod(n_point_pairs,1) > 0
error( 'The number of point pairs must be an integer.' )
else
end
end

% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
%
% Initialize Monte Carlo Runs
%
% IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

disp( ' ')

start_time = tic ;

t = now ;

disp( 'Run started at...' )
d = datetime(t, 'ConvertFrom' ,'datenum' );
disp(d)
disp( ' ')

% Initialize the 3D matrices for storing the points and vectors of each
% individual run.

is_ray_obstructed_3mat = zeros(n_point_pairs,1,n_simulation_runs) ;

%is_ray_obstructed_3mat = [] ;

obstruction_point_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

%obstruction_point_3mat = [] ;

dA1_center_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

%dA1_center_3mat = [] ;

dA2_center_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

%dA2_center_3mat = [] ;

%is_point_valid_3mat = zeros(n_point_pairs,1,n_simulation_runs) ;

%is_point_valid_3mat = [] ;

n_dA1_normal_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

%n_dA1_normal_3mat = [] ;

n_dA2_normal_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

%n_dA2_normal_3mat = [] ;

mag_root_12_valid_3mat = zeros(n_point_pairs,1,n_simulation_runs) ;

%provisional_mag_root_12_valid_3mat = zeros(n_point_pairs,1,n_simulation_runs) ;

pages_in_bogus_3mat_num = ceil( n_simulation_runs * expected_ratio_of_total_point_pairs_to_accepted_point_pairs ) ;

mag_root_12_bogus_3mat = zeros(n_point_pairs,1,pages_in_bogus_3mat_num) ;

% Calculate the area of surface 2.

% surf_2_area =
[surf_2_area] = surf_to_area(surf_2_x_mat,surf_2_y_mat,surf_2_z_mat) ;

surf_1_center_vec = [mean(mean(surf_1_x_mat)),mean(mean(surf_1_y_mat)),mean(mean (surf_1_z_mat))] ;

surf_2_center_vec = [mean(mean(surf_2_x_mat)),mean(mean(surf_2_y_mat)),mean(mean (surf_2_z_mat))] ;

% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
%
% Monte Carlo Loop
%
% MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
% CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

% For each round of calculation of the view factor...

F12_view_factor_vec = zeros(1,n_simulation_runs) ;

%n_rept = ceil(n_simulation_runs/10) ;

number_of_valid_runs = 0 ;

number_of_bogus_runs_vec = zeros(1,n_simulation_runs) ;

grand_total_point_pairs_assessed = 0 ;

% Set up the parameters determining the number of rows required for the
% Sobol matrix.

contraction_factor_denom = 1 ;

expected_ratio_of_total_point_pairs_to_accepted_point_pairs = int32 (expected_ratio_of_total_point_pairs_to_accepted_point_pairs) ;

Sobol_matrix_row_num = ceil( ( n_point_pairs * expected_ratio_of_total_point_pairs_to_accepted_point_pairs ) * ( n_simulation_runs ) * ( 1 / contraction_factor_denom ) ) ;

Sobol_matrix_row_num = int32(Sobol_matrix_row_num) ;

formatSpec = ( 'Sobol_matrix_row_num = %7u' ) ;
fprintf(formatSpec,Sobol_matrix_row_num) ;
disp( ' ')

% Determine the size of the surface 1 x matrix.

[rows_surf_1_x_mat_num,cols_surf_1_x_mat_num] = size(surf_1_x_mat) ;

rows_surf_1_x_mat_num = int32(rows_surf_1_x_mat_num) ;

cols_surf_1_x_mat_num = int32(cols_surf_1_x_mat_num) ;

% Determine the size of the surface 2 x matrix.

[rows_surf_2_x_mat_num,cols_surf_2_x_mat_num] = size(surf_2_x_mat) ;

rows_surf_2_x_mat_num = int32(rows_surf_2_x_mat_num) ;

cols_surf_2_x_mat_num = int32(cols_surf_2_x_mat_num) ;

% Generate all the quadrilaterals for all Monte Carlo cycles
% using a Sobol selection subroutine.

[aug_Sobol_mat]= ...
aug_sobol_select_8(rows_surf_1_x_mat_num,cols_surf_1_x_mat_num, ...
rows_surf_2_x_mat_num,cols_surf_2_x_mat_num, ...
Sobol_matrix_row_num) ;

whos

parfor simulation_itr = 1:n_simulation_runs

% ...perform view factor calculations until a thermodynamically valid
% view factor (i.e. F12 <= 1) is found.

is_view_factor_valid = 0 ;

Sobol_select_beginpoint = (expected_ratio_of_total_point_pairs_to_accepted_point_pairs * n_point_pairs * (simulation_itr-1)) + 1 ;

Sobol_select_endpoint = (expected_ratio_of_total_point_pairs_to_accepted_point_pairs * n_point_pairs * (simulation_itr)) ;

% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
% WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
%
% Assign Temporary Variables Within The Parfor Loop
%
% AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
% WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
% TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

% Assign the temporary Sobol matrix for this loop by extracting part of
% the main sobol matrix.

temp_aug_Sobol_mat = aug_Sobol_mat(Sobol_select_beginpoint:Sobol_select_endpoint,:) ;

Sobol_select_itr = 1 ;

% Assign temporary output variables for the current cycle of the parfor
% loop.

temp_is_ray_obstructed_3mat = zeros(n_point_pairs,1,n_simulation_runs) ;

temp_obstruction_point_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

temp_dA1_center_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

temp_dA2_center_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

%temp_is_point_valid_3mat = zeros(n_point_pairs,1,n_simulation_runs) ;

temp_n_dA1_normal_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

temp_n_dA2_normal_3mat = zeros(n_point_pairs,3,n_simulation_runs) ;

out_number_of_bogus_runs = 0 ;

out_grand_total_point_pairs_assessed = 0 ;

%temp_mag_root_12_valid_3mat = zeros(n_point_pairs,1,n_simulation_runs) ;

while is_view_factor_valid == 0
% Select the requested number of point pairs, using a probabilistic
% choice scheme.

valid_point_pairs_num = 0 ;

point_pair_itr = 1 ;

dF12_vec = zeros(n_point_pairs,1) ;

[dF12_vec, ...
temp_is_ray_obstructed_3mat,temp_obstruction_point_3mat, ...
temp_dA1_center_3mat,temp_dA2_center_3mat, ...
temp_n_dA1_normal_3mat,temp_n_dA2_normal_3mat, ...
temp_mag_root_12_valid_3mat, ...
Sobol_select_itr,point_pair_itr,valid_point_pairs_num] = ...
...
probabilistic_n_point_pairs_select_w_obstruction_3(n_point_pairs, ...
temp_aug_Sobol_mat, ...
surf_1_x_mat,surf_1_y_mat,surf_1_z_mat, ...
surf_2_x_mat,surf_2_y_mat,surf_2_z_mat, ...
movement_of_ray_relative_to_center_of_surface_1, ...
movement_of_ray_relative_to_center_of_surface_2, ...
surf_1_center_vec,surf_2_center_vec, ...
obs_surf_x_mat,obs_surf_y_mat,obs_surf_z_mat, ...
simulation_itr, ...
Sobol_matrix_row_num, ...
Sobol_select_itr,point_pair_itr,valid_point_pairs_num, ...
dF12_vec, ...
temp_is_ray_obstructed_3mat,temp_obstruction_point_3mat, ...
temp_dA1_center_3mat,temp_dA2_center_3mat, ...
temp_n_dA1_normal_3mat,temp_n_dA2_normal_3mat) ;

%point_pair_itr = point_pair_itr ;

%nonzero_obstruction_point_3mat = obstruction_point_3mat(obstruction_point_3mat(:,:, simulation_itr)~=[0,0,0])

% Calculate the view factor that results from the given set.

F12_view_factor_value = ( surf_2_area / valid_point_pairs_num ) .* sum(dF12_vec) ;

disp( ' ')

point_pair_itr = point_pair_itr - 1 ;

% Is the resulting view factor less than 1? If so, ...

if F12_view_factor_value <= 1
% ...keep the value, and increment the number of valid runs by
% one.
is_view_factor_valid = 1 ;

number_of_valid_runs = number_of_valid_runs + 1
disp( ' ')

F12_view_factor_vec(1,simulation_itr) = F12_view_factor_value ;

out_is_ray_obstructed_mat = temp_is_ray_obstructed_3mat(:,:,simulation_itr) ;

out_obstruction_point_mat = temp_obstruction_point_3mat(:,:,simulation_itr) ;

out_dA1_center_mat = temp_dA1_center_3mat(:,:,simulation_itr) ;

out_dA2_center_mat = temp_dA2_center_3mat(:,:,simulation_itr) ;

out_n_dA1_normal_mat = temp_n_dA1_normal_3mat(:,:,simulation_itr) ;

out_n_dA2_normal_mat = temp_n_dA2_normal_3mat(:,:,simulation_itr) ;

out_mag_root_12_valid_mat = temp_mag_root_12_valid_3mat(:,:,simulation_itr) ;

out_mag_root_12_bogus_mat = zeros(n_point_pairs,1) ;

% Otherwise...
else

keep_fixing = 1;

fixing_attempt_number = 1 ;

while keep_fixing == 1

% ...determine if the preceding bogus run is "fixable," using a
% probabilistic choice scheme.

%fixing_attempt_number = fixing_attempt_number

% FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
% BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
%
% Fixing Bogus Runs
%
% FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
% BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

% Let the probability of fixing the preceding bogus run equal
% the fourth root of 1/F12. This reflects the notion that a
% bogus run is more likely to be fixable if its value is closer
% to 1; the fourth root increases the probability of a "fix"
% being chosen.

prob_fixable = ( 1 / F12_view_factor_value ) ^ 0.25 ;

% Choose a random number.

rand_num_4 = rand() ;

% If the random number is less than, or equal to, the
% probability that the previous bogus run is fixable...

if rand_num_4 <= prob_fixable
% ... the preceding bogus run is deemed fixable, and an
% attempt is made to correct it.

disp( ' ')
disp( 'Hmmm. Let us see if we can fix that...' )
disp( ' ')

old_F12_view_factor_value = F12_view_factor_value ;

% sappsappsappsappsappsappsappsappsappsappsappsappsapp
%
% --sort all point pairs--
%
% sappsappsappsappsappsappsappsappsappsappsappsappsapp

% Sort the point pairs from the preceding run by descending
% size of their "differential view factor" values.

[sorted_dF12_vec,sorted_dF12_vec_ind_vec] = sort(dF12_vec,1, 'ascend') ;

%size_is_ray_obstructed_3_mat = size(is_ray_obstructed_3mat)

temp_is_ray_obstructed_3mat(:,:,simulation_itr) = temp_is_ray_obstructed_3mat(sorted_dF12_vec_ind_vec(1:n_point_pairs,1),:,simulatio n_itr) ;

temp_obstruction_point_3mat(:,:,simulation_itr) = temp_obstruction_point_3mat(sorted_dF12_vec_ind_vec(1:n_point_pairs,1),:,simulatio n_itr) ;

temp_dA1_center_3mat(:,:,simulation_itr) = temp_dA1_center_3mat (sorted_dF12_vec_ind_vec(1:n_point_pairs,1),:,simulation_itr) ;

temp_dA2_center_3mat(:,:,simulation_itr) = temp_dA2_center_3mat (sorted_dF12_vec_ind_vec(1:n_point_pairs,1),:,simulation_itr) ;

temp_n_dA1_normal_3mat(:,:,simulation_itr) = temp_n_dA1_normal_3mat (sorted_dF12_vec_ind_vec(1:n_point_pairs,1),:,simulation_itr) ;

temp_n_dA2_normal_3mat(:,:,simulation_itr) = temp_n_dA2_normal_3mat (sorted_dF12_vec_ind_vec(1:n_point_pairs,1),:,simulation_itr) ;

temp_mag_root_12_valid_3mat(:,:,simulation_itr) = temp_mag_root_12_valid_3mat(sorted_dF12_vec_ind_vec(1:n_point_pairs,1),:,simulatio n_itr) ;

% Find the point pairs that push the associated value of F12
% over 1.

%sorted_dF12_vec = sorted_dF12_vec ;

cumsum_sorted_dF12_vec = cumsum(( surf_2_area / valid_point_pairs_num ) . *sorted_dF12_vec) ;

bogus_dF12_ind_vec = find(cumsum_sorted_dF12_vec > 1) ;

if max(size(bogus_dF12_ind_vec)) < floor(n_point_pairs/2)
disp( ' ')
disp( 'Number of bogus point-pairs is *less* than half the total number of point pairs.' )
disp( ' ')
num_bogus_dF12_points = 2 * max(size(bogus_dF12_ind_vec))
else
disp( ' ')
disp( 'Number of bogus point-pairs is MORE than half the total number of point pairs.' )
disp( ' ')
num_bogus_dF12_points = max(size(bogus_dF12_ind_vec))
end

% dbppdbppdbppdbppdbppdbppdbppdbppdbppdbppdbppdbppdbpp
%
% --ditch bogus point pairs--
%
% dbppdbppdbppdbppdbppdbppdbppdbppdbppdbppdbppdbppdbpp

% Remove those point pairs, and retain all the others.

valid_point_pairs_num = valid_point_pairs_num - num_bogus_dF12_points ;

point_pair_itr = n_point_pairs - num_bogus_dF12_points + 1;

valid_dF12_vec = sorted_dF12_vec(1:valid_point_pairs_num,1) ;

valid_dF12_vec = vertcat(valid_dF12_vec,zeros(num_bogus_dF12_points,1)) ;

temp_is_ray_obstructed_3mat(valid_point_pairs_num+1:n_point_pairs,:, simulation_itr) = zeros(num_bogus_dF12_points,1) ;

temp_obstruction_point_3mat(valid_point_pairs_num+1:n_point_pairs,:, simulation_itr) = zeros(num_bogus_dF12_points,3) ;

temp_dA1_center_3mat(valid_point_pairs_num+1:n_point_pairs,:, simulation_itr) = zeros(num_bogus_dF12_points,3) ;

temp_dA2_center_3mat(valid_point_pairs_num+1:n_point_pairs,:, simulation_itr) = zeros(num_bogus_dF12_points,3) ;

temp_n_dA1_normal_3mat(valid_point_pairs_num+1:n_point_pairs,:, simulation_itr) = zeros(num_bogus_dF12_points,3) ;

temp_n_dA2_normal_3mat(valid_point_pairs_num+1:n_point_pairs,:, simulation_itr) = zeros(num_bogus_dF12_points,3) ;

temp_mag_root_12_valid_3mat(valid_point_pairs_num+1:n_point_pairs,:, simulation_itr) = zeros(num_bogus_dF12_points,1) ;

% Find additional point pairs, to replace the ones that have
% just been discarded.

[fix_dF12_vec, ...
fix_is_ray_obstructed_3mat,fix_obstruction_point_3mat, ...
fix_dA1_center_3mat,fix_dA2_center_3mat, ...
fix_n_dA1_normal_3mat,fix_n_dA2_normal_3mat, ...
fix_mag_root_12_valid_3mat, ...
Sobol_select_itr,point_pair_itr,valid_point_pairs_num] = ...
probabilistic_n_point_pairs_select_w_obstruction_3(n_point_pairs, ...
aug_Sobol_mat, ...
surf_1_x_mat,surf_1_y_mat,surf_1_z_mat, ...
surf_2_x_mat,surf_2_y_mat,surf_2_z_mat, ...
movement_of_ray_relative_to_center_of_surface_1, ...
movement_of_ray_relative_to_center_of_surface_2, ...
surf_1_center_vec,surf_2_center_vec, ...
obs_surf_x_mat,obs_surf_y_mat,obs_surf_z_mat, ...
simulation_itr, ...
Sobol_matrix_row_num, ...
Sobol_select_itr,point_pair_itr,valid_point_pairs_num, ...
valid_dF12_vec, ...
temp_is_ray_obstructed_3mat,temp_obstruction_point_3mat, ...
temp_dA1_center_3mat,temp_dA2_center_3mat, ...
temp_n_dA1_normal_3mat,temp_n_dA2_normal_3mat);

% Calculate the resulting view factor.

%fix_dF12_vec = fix_dF12_vec

%fix_sum_of_diff_view_factors = sum(fix_dF12_vec) ;

fix_F12_view_factor_value = ( surf_2_area / valid_point_pairs_num ) * sum (fix_dF12_vec) ;
disp( ' ')

point_pair_itr = point_pair_itr - 1 ;

% Is the associated view factor less than or equal to
% 1 after the "fixing" step is complete?
% If so...

if fix_F12_view_factor_value <= 1
% ...this simulation run is done; prepare the
% associated results for output, and move on to the
% next simulation run.

keep_fixing = 0 ;

is_view_factor_valid = 1 ;

number_of_valid_runs = number_of_valid_runs + 1

F12_view_factor_vec(1,simulation_itr) = fix_F12_view_factor_value ;

% formatSpec = 'F12 value = %6.4f';
% fprintf(formatSpec,fix_F12_view_factor_value);
% disp(' ')

out_is_ray_obstructed_mat = fix_is_ray_obstructed_3mat(:,:, simulation_itr) ;

out_obstruction_point_mat = fix_obstruction_point_3mat(:,:, simulation_itr) ;

out_dA1_center_mat = fix_dA1_center_3mat(:,:,simulation_itr) ;

out_dA2_center_mat = fix_dA2_center_3mat(:,:,simulation_itr) ;

out_n_dA1_normal_mat = fix_n_dA1_normal_3mat(:,:,simulation_itr) ;

out_n_dA2_normal_mat = fix_n_dA2_normal_3mat(:,:,simulation_itr) ;

out_mag_root_12_valid_mat = fix_mag_root_12_valid_3mat(:,:, simulation_itr) ;

out_mag_root_12_bogus_mat = zeros(n_point_pairs,1) ;

%
% F12_view_factor_vec(1,simulation_itr) = fix_F12_view_factor_value ;
%
% is_ray_obstructed_3mat = fix_is_ray_obstructed_3mat ;
%
% obstruction_point_3mat = fix_obstruction_point_3mat ;
%
% dA1_center_3mat = fix_dA1_center_3mat;
%
% dA2_center_3mat = fix_dA2_center_3mat;
%
% n_dA1_normal_3mat = fix_n_dA1_normal_3mat;
%
% n_dA2_normal_3mat = fix_n_dA2_normal_3mat;
%
% mag_root_12_valid_3mat = fix_mag_root_12_valid_3mat;

% Otherwise...
else
% Determine whether the revised set of point pairs yields
% an F12 closer to 1.

% If the revised set gives an F12 that is closer to 1...
if fix_F12_view_factor_value < old_F12_view_factor_value
% ...keep the revised set of point pairs, and
% repeat the fixing cycle.

disp( ' ')
disp( 'Well, that *is* better....' )
disp( ' ')

out_number_of_bogus_runs = out_number_of_bogus_runs + 1

F12_view_factor_vec(1,simulation_itr) = fix_F12_view_factor_value ;

temp_is_ray_obstructed_3mat = fix_is_ray_obstructed_3mat ;

temp_obstruction_point_3mat = fix_obstruction_point_3mat ;

temp_dA1_center_3mat = fix_dA1_center_3mat;

temp_dA2_center_3mat = fix_dA2_center_3mat;

temp_n_dA1_normal_3mat = fix_n_dA1_normal_3mat;

temp_n_dA2_normal_3mat = fix_n_dA2_normal_3mat;

temp_mag_root_12_valid_3mat = fix_mag_root_12_valid_3mat ;

out_mag_root_12_bogus_mat = temp_mag_root_12_valid_3mat(:,1, simulation_itr) ;

% Otherwise...
else
% ...the original set of point pairs gives an F12
% that is closer to 1. Proceed
% to create and test an entirely new set of point
% pairs.

disp( ' ')
disp( 'Ach. Never mind.' )
disp( ' ')
disp( ' ')

keep_fixing = 0 ;

out_number_of_bogus_runs = out_number_of_bogus_runs + 1

out_mag_root_12_bogus_mat = temp_mag_root_12_valid_3mat(:,1, simulation_itr) ;

% Periodically update the user on the number of bogus runs that
% has been generated.

% if mod(number_of_bogus_runs,100) ==
% number_of_bogus_runs = number_of_bogus_runs
% else
% end

end

end

% Otherwise...
else
% ... the preceding bogus run is deemed UNfixable, and NO
% attempt will be made to correct it.

disp( ' ')
disp( 'All righty. Moving right along...' )
disp( ' ')

keep_fixing = 0 ;

out_number_of_bogus_runs = out_number_of_bogus_runs + 1

out_mag_root_12_bogus_mat = temp_mag_root_12_valid_3mat(:,1, simulation_itr) ;

end

fixing_attempt_number = fixing_attempt_number + 1 ;

end

end

end

out_grand_total_point_pairs_assessed = Sobol_select_itr ;

% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
% OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
%
% Return Parfor Loop Output
%
% RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
% PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
% LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
% OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

% formatSpec = 'F12 value for cycle %3u = %6.4f';
%
% fprintf(formatSpec,simulation_itr,F12_view_factor_vec(1,simulation_itr))
%
% disp(' ')

%F12_view_factor_value = F12_view_factor_vec(1,simulation_itr)

is_ray_obstructed_3mat(:,:,simulation_itr) = out_is_ray_obstructed_mat ;

obstruction_point_3mat(:,:,simulation_itr) = out_obstruction_point_mat;

dA1_center_3mat(:,:,simulation_itr) = out_dA1_center_mat ;

dA2_center_3mat(:,:,simulation_itr) = out_dA2_center_mat ;

dA1_normal_3mat(:,:,simulation_itr) = out_n_dA1_normal_mat ;

dA2_normal_3mat(:,:,simulation_itr) = out_n_dA2_normal_mat ;

mag_root_12_valid_3mat(:,:,simulation_itr) = out_mag_root_12_valid_mat ;

mag_root_12_bogus_3mat(:,:,simulation_itr) = out_mag_root_12_bogus_mat ;

number_of_bogus_runs_vec(1,simulation_itr) = number_of_bogus_runs_vec(1,simulation_itr) + out_number_of_bogus_runs ;

grand_total_point_pairs_assessed = grand_total_point_pairs_assessed + out_grand_total_point_pairs_assessed ;


% if mod(number_of_bogus_runs,100) == 0
% number_of_bogus_runs = number_of_bogus_runs
% else
% end

% Periodically update the user on the status of the calculation.

% if mod(simulation_itr,n_rept) == 0
% percent_done = 100*simulation_itr/n_simulation_runs ;
% formatSpec = 'Run is %4.2f percent done.' ;
% disp(' ')
% fprintf(formatSpec,percent_done)
% disp(' ')
% else
% end

end

% Take the absolute value of the probabilities in the augmented Sobol
% matrix, so that the physically reasonable points are made available for
% use by subsequent library-using Monte Carlo codes.

%aug_Sobol_mat(:,5) = abs(aug_Sobol_mat(:,5)) ;

% Output the relevant data from the Monte Carlo run that has just been
% completed.

%aug_Sobol_mat_col_5 = aug_Sobol_mat(:,5)

%figure
%histogram(aug_Sobol_mat(:,5))

disp( ' ')
disp( ' ')
disp( 'Monte Carlo run is done.' )
disp( ' ')
disp( ' ')

formatSpec = 'The number of valid runs is %5u.' ;
fprintf(formatSpec,number_of_valid_runs)
disp( ' ')

number_of_bogus_runs = sum(number_of_bogus_runs_vec);

formatSpec = 'The number of bogus runs is %5u.' ;
fprintf(formatSpec,number_of_bogus_runs)
disp( ' ')

avg_F12 = mean(F12_view_factor_vec) ;

formatSpec = 'The average view factor across all cycles is %6.4f.' ;
fprintf(formatSpec,avg_F12)
disp( ' ')

error = 100*abs(avg_F12-true_val)/true_val ;

formatSpec = 'The percent error of the calculated F12, compared to the known value, is %6.3f percent.' ;
fprintf(formatSpec,error)
disp( ' ')

std_F12 = std(F12_view_factor_vec) ;

formatSpec = 'The standard deviation of the F12 values for all cycles is %6.4f.' ;
fprintf(formatSpec,std_F12)
disp( ' ')

RSD = 100*(std_F12/avg_F12) ;

formatSpec = 'The relative standard deviation of the F12 values is %6.4f percent.' ;
fprintf(formatSpec,RSD)
disp( ' ')

run_time_in_s = toc(start_time) ;

formatSpec = 'The total run time in s is %7.1f.' ;
fprintf(formatSpec,run_time_in_s)
disp( ' ')

total_valid_point_pairs_assessed = n_point_pairs * n_simulation_runs ;

formatSpec = 'The total number of valid point pairs that has been assessed is %6u.' ;
fprintf(formatSpec,total_valid_point_pairs_assessed)
disp( ' ')

%grand_total_point_pairs_assessed = Sobol_select_itr

formatSpec = 'The grand total of all point pairs that have been assessed is %6u.' ;
fprintf(formatSpec,grand_total_point_pairs_assessed)
disp( ' ')

end
