function [ V_prime,V_prime_r,V_prime_theta ] = V_prime_r_theta( theta_s,delta,Mach_2,gamma )
%
% Usage:
%
% [ V_prime,V_prime_r,V_prime_theta ] = V_prime_r_theta( theta_s,delta,Mach_2,gamma )
% The purpose of this function is to find the nondimensional velocity of
% flow immediately behind an oblique shock, generated by a cone flying
% at zero angle of attack. It also generates the corresponding angular
% and radial components of this nondimensional velocity.
%
% Input terms:
% theta_s=; delta=; Mach_2=; gamma=;
% where
% theta_s = the shockwave angle of the oblique shock generated by
% the cone;
% delta = the angle of deflection of the incoming flow, created
% by the shockwave;
% Mach_2 = the Mach number of the flow immediately behind the
% shock;
% and
% gamma = the heat capacity ratio of the gas the cone is flying
% through.

% This subroutine corresponds to step 2 of 5 in the algorithm for numerical
% flowfield calculations, as given by Anderson (Modern Compressible Flow,
% Ch. 10.4, pp. 371-2).

% Find the nondimensional velocity, V_prime, of the flow directly behind
% the shock.

V_prime = ( ( 2 / ((gamma-1)*(Mach_2^2)) ) + 1 ) ^ (-1/2) ;

% Find the internal angle, theta_int, of the triangle defined by V_prime_r
% and V_prime_theta.

theta_int = theta_s - delta ;

% Find the radial component of the nondimensional velocity, V_prime_r.

V_prime_r = cos(theta_int) * V_prime ;

% Find the angular component of the nondimensional velocity, V_prime_theta.

V_prime_theta = sin(theta_int) * V_prime ;

end
